// Autogenerated by gen_jumbo.c

#include "conf.h"

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#ifndef SKIP_BSOCKET_C
#include XSTR(NAPPGUI_SRC/osbs/bsocket.c)
#endif // SKIP_BSOCKET_C

#ifndef SKIP_BSOCKET_C
#include XSTR(NAPPGUI_SRC/osbs/unix/bsocket.c)
#endif // SKIP_BSOCKET_C

#ifndef SKIP_BTIME_C
#include XSTR(NAPPGUI_SRC/osbs/unix/btime.c)
#endif // SKIP_BTIME_C

#ifndef SKIP_BMUTEX_C
#include XSTR(NAPPGUI_SRC/osbs/unix/bmutex.c)
#endif // SKIP_BMUTEX_C

#ifndef SKIP_BTHREAD_C
#include XSTR(NAPPGUI_SRC/osbs/unix/bthread.c)
#endif // SKIP_BTHREAD_C

#ifndef SKIP_DLIB_C
#include XSTR(NAPPGUI_SRC/osbs/unix/dlib.c)
#endif // SKIP_DLIB_C

#ifndef SKIP_BFILE_C
#include XSTR(NAPPGUI_SRC/osbs/unix/bfile.c)
#endif // SKIP_BFILE_C

#ifndef SKIP_SINFO_C
#include XSTR(NAPPGUI_SRC/osbs/unix/sinfo.c)
#endif // SKIP_SINFO_C

#ifndef SKIP_BPROC_C
#define i_create i_create_bproc_c
#include XSTR(NAPPGUI_SRC/osbs/unix/bproc.c)
#undef i_create
#endif // SKIP_BPROC_C

#ifndef SKIP_LOG_C
#include XSTR(NAPPGUI_SRC/osbs/log.c)
#endif // SKIP_LOG_C

#ifndef SKIP_OSBS_C
#define i_NUM_USERS i_NUM_USERS_osbs_c
#include XSTR(NAPPGUI_SRC/osbs/osbs.c)
#undef i_NUM_USERS
#endif // SKIP_OSBS_C

#ifndef SKIP_SINFO_C
#include XSTR(NAPPGUI_SRC/osbs/linux/sinfo.c)
#endif // SKIP_SINFO_C

#ifndef SKIP_HFILE_C
#include XSTR(NAPPGUI_SRC/core/hfile.c)
#endif // SKIP_HFILE_C

#ifndef SKIP_REGEX_C
#include XSTR(NAPPGUI_SRC/core/regex.c)
#endif // SKIP_REGEX_C

#ifndef SKIP_NFA_C
#define func_copy func_copy_nfa_c
#define func_read func_read_nfa_c
#define func_remove func_remove_nfa_c
#define func_write func_write_nfa_c
#define func_compare func_compare_nfa_c
#include XSTR(NAPPGUI_SRC/core/nfa.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#endif // SKIP_NFA_C

#ifndef SKIP_CLOCK_C
#include XSTR(NAPPGUI_SRC/core/clock.c)
#endif // SKIP_CLOCK_C

#ifndef SKIP_HEAP_C
#define i_next_pow2 i_next_pow2_heap_c
#include XSTR(NAPPGUI_SRC/core/heap.c)
#undef i_next_pow2
#endif // SKIP_HEAP_C

#ifndef SKIP_DATE_C
#include XSTR(NAPPGUI_SRC/core/date.c)
#endif // SKIP_DATE_C

#ifndef SKIP_STRINGS_C
#include XSTR(NAPPGUI_SRC/core/strings.c)
#endif // SKIP_STRINGS_C

#ifndef SKIP_TFILTER_C
#define _state_t _state_t_tfilter_c
#define stSTART stSTART_tfilter_c
#define stZERO stZERO_tfilter_c
#define stREAL stREAL_tfilter_c
#define gui_state_t gui_state_t_tfilter_c
#include XSTR(NAPPGUI_SRC/core/tfilter.c)
#undef _state_t
#undef stSTART
#undef stZERO
#undef stREAL
#undef gui_state_t
#endif // SKIP_TFILTER_C

#ifndef SKIP_BUFFER_C
#include XSTR(NAPPGUI_SRC/core/buffer.c)
#endif // SKIP_BUFFER_C

#ifndef SKIP_DBIND_C
#define func_copy func_copy_dbind_c
#define func_read func_read_dbind_c
#define func_remove func_remove_dbind_c
#define func_write func_write_dbind_c
#define func_compare func_compare_dbind_c
#define func_destroy func_destroy_dbind_c
#define i_EPSILON i_EPSILON_dbind_c
#define i_write_container i_write_container_dbind_c
#define i_destroy_data i_destroy_data_dbind_c
#define i_set_bool i_set_bool_dbind_c
#define i_set_real i_set_real_dbind_c
#define i_set_enum i_set_enum_dbind_c
#define i_create i_create_dbind_c
#include XSTR(NAPPGUI_SRC/core/dbind.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef func_destroy
#undef i_EPSILON
#undef i_write_container
#undef i_destroy_data
#undef i_set_bool
#undef i_set_real
#undef i_set_enum
#undef i_create
#endif // SKIP_DBIND_C

#ifndef SKIP_KEYBUF_C
#include XSTR(NAPPGUI_SRC/core/keybuf.c)
#endif // SKIP_KEYBUF_C

#ifndef SKIP_OBJ_C
#include XSTR(NAPPGUI_SRC/core/obj.c)
#endif // SKIP_OBJ_C

#ifndef SKIP_LEX_C
#define _state_t _state_t_lex_c
#define stSTART stSTART_lex_c
#define stZERO stZERO_lex_c
#define stREAL stREAL_lex_c
#define gui_state_t gui_state_t_lex_c
#include XSTR(NAPPGUI_SRC/core/lex.c)
#undef _state_t
#undef stSTART
#undef stZERO
#undef stREAL
#undef gui_state_t
#endif // SKIP_LEX_C

#ifndef SKIP_RBTREE_C
#define i_type_t i_type_t_rbtree_c
#include XSTR(NAPPGUI_SRC/core/rbtree.c)
#undef i_type_t
#endif // SKIP_RBTREE_C

#ifndef SKIP_BHASH_C
#include XSTR(NAPPGUI_SRC/core/bhash.c)
#endif // SKIP_BHASH_C

#ifndef SKIP_RESPACK_C
#define func_copy func_copy_respack_c
#define func_read func_read_respack_c
#define func_remove func_remove_respack_c
#define func_write func_write_respack_c
#define func_compare func_compare_respack_c
#include XSTR(NAPPGUI_SRC/core/respack.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#endif // SKIP_RESPACK_C

#ifndef SKIP_ARRAY_C
#define i_destroy i_destroy_array_c
#define i_next_pow2 i_next_pow2_array_c
#include XSTR(NAPPGUI_SRC/core/array.c)
#undef i_destroy
#undef i_next_pow2
#endif // SKIP_ARRAY_C

#ifndef SKIP_STREAM_C
#define i_type_t i_type_t_stream_c
#define i_next_pow2 i_next_pow2_stream_c
#define i_write_binary i_write_binary_stream_c
#include XSTR(NAPPGUI_SRC/core/stream.c)
#undef i_type_t
#undef i_next_pow2
#undef i_write_binary
#endif // SKIP_STREAM_C

#ifndef SKIP_OGL3DIMP_C
#include XSTR(NAPPGUI_SRC/ogl3d/gtk/ogl3dimp.c)
#endif // SKIP_OGL3DIMP_C

#ifndef SKIP_GLEW_C
#include XSTR(NAPPGUI_SRC/ogl3d/glew.c)
#endif // SKIP_GLEW_C

#ifndef SKIP_OGL3D_C
#define i_NUM_USERS i_NUM_USERS_ogl3d_c
#include XSTR(NAPPGUI_SRC/ogl3d/ogl3d.c)
#undef i_NUM_USERS
#endif // SKIP_OGL3D_C

#ifndef SKIP_IMAGE_C
#define i_codec i_codec_image_c
#include XSTR(NAPPGUI_SRC/draw2d/image.c)
#undef i_codec
#endif // SKIP_IMAGE_C

#ifndef SKIP_DRAW_GTK_C
#define i_color i_color_draw_gtk_c
#define i_align i_align_draw_gtk_c
#include XSTR(NAPPGUI_SRC/draw2d/gtk/draw_gtk.c)
#undef i_color
#undef i_align
#endif // SKIP_DRAW_GTK_C

#ifndef SKIP_OSFONT_C
#define i_PANGO_TO_PIXELS i_PANGO_TO_PIXELS_osfont_c
#define i_device_to_pixels i_device_to_pixels_osfont_c
#include XSTR(NAPPGUI_SRC/draw2d/gtk/osfont.c)
#undef i_PANGO_TO_PIXELS
#undef i_device_to_pixels
#endif // SKIP_OSFONT_C

#ifndef SKIP_DCTX_GTK_C
#define i_color i_color_dctx_gtk_c
#include XSTR(NAPPGUI_SRC/draw2d/gtk/dctx_gtk.c)
#undef i_color
#endif // SKIP_DCTX_GTK_C

#ifndef SKIP_OSIMAGE_C
#define i_codec i_codec_osimage_c
#include XSTR(NAPPGUI_SRC/draw2d/gtk/osimage.c)
#undef i_codec
#endif // SKIP_OSIMAGE_C

#ifndef SKIP_FONT_C
#include XSTR(NAPPGUI_SRC/draw2d/font.c)
#endif // SKIP_FONT_C

#ifndef SKIP_DCTX_C
#include XSTR(NAPPGUI_SRC/draw2d/dctx.c)
#endif // SKIP_DCTX_C

#ifndef SKIP_DRAW2D_C
#define func_copy func_copy_draw2d_c
#define func_read func_read_draw2d_c
#define func_remove func_remove_draw2d_c
#define func_write func_write_draw2d_c
#define func_compare func_compare_draw2d_c
#define i_NUM_USERS i_NUM_USERS_draw2d_c
#include XSTR(NAPPGUI_SRC/draw2d/draw2d.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_NUM_USERS
#endif // SKIP_DRAW2D_C

#ifndef SKIP_PALETTE_C
#include XSTR(NAPPGUI_SRC/draw2d/palette.c)
#endif // SKIP_PALETTE_C

#ifndef SKIP_GUICTX_C
#include XSTR(NAPPGUI_SRC/draw2d/guictx.c)
#endif // SKIP_GUICTX_C

#ifndef SKIP_COLOR_C
#include XSTR(NAPPGUI_SRC/draw2d/color.c)
#endif // SKIP_COLOR_C

#ifndef SKIP_PIXBUF_C
#include XSTR(NAPPGUI_SRC/draw2d/pixbuf.c)
#endif // SKIP_PIXBUF_C

#ifndef SKIP_IMGUTIL_C
#include XSTR(NAPPGUI_SRC/draw2d/imgutil.c)
#endif // SKIP_IMGUTIL_C

#ifndef SKIP_BMEM_C
#include XSTR(NAPPGUI_SRC/sewer/bmem.c)
#endif // SKIP_BMEM_C

#ifndef SKIP_QSORT_C
#include XSTR(NAPPGUI_SRC/sewer/qsort.c)
#endif // SKIP_QSORT_C

#ifndef SKIP_UNICODE_C
#include XSTR(NAPPGUI_SRC/sewer/unicode.c)
#endif // SKIP_UNICODE_C

#ifndef SKIP_CASSERT_C
#include XSTR(NAPPGUI_SRC/sewer/cassert.c)
#endif // SKIP_CASSERT_C

#ifndef SKIP_BSTDIMP_C
#include XSTR(NAPPGUI_SRC/sewer/unix/bstdimp.c)
#endif // SKIP_BSTDIMP_C

#ifndef SKIP_BMEM_UNIX_C
#include XSTR(NAPPGUI_SRC/sewer/unix/bmem_unix.c)
#endif // SKIP_BMEM_UNIX_C

#ifndef SKIP_BLIB_C
#include XSTR(NAPPGUI_SRC/sewer/blib.c)
#endif // SKIP_BLIB_C

#ifndef SKIP_SEWER_C
#define i_NUM_USERS i_NUM_USERS_sewer_c
#include XSTR(NAPPGUI_SRC/sewer/sewer.c)
#undef i_NUM_USERS
#endif // SKIP_SEWER_C

#ifndef SKIP_TYPES_C
#include XSTR(NAPPGUI_SRC/sewer/types.c)
#endif // SKIP_TYPES_C

#ifndef SKIP_PTR_C
#include XSTR(NAPPGUI_SRC/sewer/ptr.c)
#endif // SKIP_PTR_C

#ifndef SKIP_HTTPREQ_C
#define func_copy func_copy_httpreq_c
#define func_read func_read_httpreq_c
#define func_remove func_remove_httpreq_c
#define func_write func_write_httpreq_c
#define func_compare func_compare_httpreq_c
#define i_create i_create_httpreq_c
#include XSTR(NAPPGUI_SRC/inet/httpreq.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_create
#endif // SKIP_HTTPREQ_C

#ifndef SKIP_OSHTTPREQ_C
#include XSTR(NAPPGUI_SRC/inet/linux/oshttpreq.c)
#endif // SKIP_OSHTTPREQ_C

#ifndef SKIP_INET_C
#define i_NUM_USERS i_NUM_USERS_inet_c
#include XSTR(NAPPGUI_SRC/inet/inet.c)
#undef i_NUM_USERS
#endif // SKIP_INET_C

#ifndef SKIP_EDIT_C
#define i_OnFilter i_OnFilter_edit_c
#define i_OnChange i_OnChange_edit_c
#define i_OnFocus i_OnFocus_edit_c
#define i_create i_create_edit_c
#include XSTR(NAPPGUI_SRC/gui/edit.c)
#undef i_OnFilter
#undef i_OnChange
#undef i_OnFocus
#undef i_create
#endif // SKIP_EDIT_C

#ifndef SKIP_IMAGEVIEW_C
#define i_OnDraw i_OnDraw_imageview_c
#define i_OnEnter i_OnEnter_imageview_c
#define i_OnExit i_OnExit_imageview_c
#define i_OnClick i_OnClick_imageview_c
#define i_OnAcceptFocus i_OnAcceptFocus_imageview_c
#define i_destroy_data i_destroy_data_imageview_c
#define i_create_data i_create_data_imageview_c
#include XSTR(NAPPGUI_SRC/gui/imageview.c)
#undef i_OnDraw
#undef i_OnEnter
#undef i_OnExit
#undef i_OnClick
#undef i_OnAcceptFocus
#undef i_destroy_data
#undef i_create_data
#endif // SKIP_IMAGEVIEW_C

#ifndef SKIP_SCROLLVIEW_C
#include XSTR(NAPPGUI_SRC/gui/scrollview.c)
#endif // SKIP_SCROLLVIEW_C

#ifndef SKIP_TABLEVIEW_C
#define _ctype_t _ctype_t_tableview_c
#define ctype_t ctype_t_tableview_c
#define i_OnDraw i_OnDraw_tableview_c
#define i_OnOverlay i_OnOverlay_tableview_c
#define i_OnSize i_OnSize_tableview_c
#define i_OnExit i_OnExit_tableview_c
#define i_OnMove i_OnMove_tableview_c
#define i_OnDown i_OnDown_tableview_c
#define i_OnUp i_OnUp_tableview_c
#define i_OnDrag i_OnDrag_tableview_c
#define i_OnKeyDown i_OnKeyDown_tableview_c
#define i_OnKeyUp i_OnKeyUp_tableview_c
#define i_OnFocus i_OnFocus_tableview_c
#define i_OnScroll i_OnScroll_tableview_c
#define i_destroy_data i_destroy_data_tableview_c
#define func_copy func_copy_tableview_c
#define func_read func_read_tableview_c
#define func_remove func_remove_tableview_c
#define func_write func_write_tableview_c
#define func_compare func_compare_tableview_c
#define i_BOTTOM_PADDING i_BOTTOM_PADDING_tableview_c
#define i_create_data i_create_data_tableview_c
#define i_document_size i_document_size_tableview_c
#define i_select i_select_tableview_c
#define i_update_sel_top i_update_sel_top_tableview_c
#define i_update_sel_bottom i_update_sel_bottom_tableview_c
#include XSTR(NAPPGUI_SRC/gui/tableview.c)
#undef _ctype_t
#undef ctype_t
#undef i_OnDraw
#undef i_OnOverlay
#undef i_OnSize
#undef i_OnExit
#undef i_OnMove
#undef i_OnDown
#undef i_OnUp
#undef i_OnDrag
#undef i_OnKeyDown
#undef i_OnKeyUp
#undef i_OnFocus
#undef i_OnScroll
#undef i_destroy_data
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_BOTTOM_PADDING
#undef i_create_data
#undef i_document_size
#undef i_select
#undef i_update_sel_top
#undef i_update_sel_bottom
#endif // SKIP_TABLEVIEW_C

#ifndef SKIP_POPUP_C
#define i_OnSelect i_OnSelect_popup_c
#include XSTR(NAPPGUI_SRC/gui/popup.c)
#undef i_OnSelect
#endif // SKIP_POPUP_C

#ifndef SKIP_UPDOWN_C
#define i_OnClick i_OnClick_updown_c
#include XSTR(NAPPGUI_SRC/gui/updown.c)
#undef i_OnClick
#endif // SKIP_UPDOWN_C

#ifndef SKIP_COMBO_C
#define i_OnFilter i_OnFilter_combo_c
#define i_OnChange i_OnChange_combo_c
#define i_OnFocus i_OnFocus_combo_c
#define i_OnSelect i_OnSelect_combo_c
#include XSTR(NAPPGUI_SRC/gui/combo.c)
#undef i_OnFilter
#undef i_OnChange
#undef i_OnFocus
#undef i_OnSelect
#endif // SKIP_COMBO_C

#ifndef SKIP_GBIND_C
#define func_copy func_copy_gbind_c
#define func_read func_read_gbind_c
#define func_remove func_remove_gbind_c
#define func_write func_write_gbind_c
#define func_compare func_compare_gbind_c
#define i_set_bool i_set_bool_gbind_c
#define i_set_real i_set_real_gbind_c
#define i_set_enum i_set_enum_gbind_c
#define i_set_empty i_set_empty_gbind_c
#include XSTR(NAPPGUI_SRC/gui/gbind.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_set_bool
#undef i_set_real
#undef i_set_enum
#undef i_set_empty
#endif // SKIP_GBIND_C

#ifndef SKIP_WINDOW_C
#define i_destroy i_destroy_window_c
#include XSTR(NAPPGUI_SRC/gui/window.c)
#undef i_destroy
#endif // SKIP_WINDOW_C

#ifndef SKIP_SLIDER_C
#define i_create i_create_slider_c
#include XSTR(NAPPGUI_SRC/gui/slider.c)
#undef i_create
#endif // SKIP_SLIDER_C

#ifndef SKIP_GUI_C
#define _icon_t _icon_t_gui_c
#define icon_t icon_t_gui_c
#define func_copy func_copy_gui_c
#define func_read func_read_gui_c
#define func_remove func_remove_gui_c
#define func_write func_write_gui_c
#define func_compare func_compare_gui_c
#define func_destroy func_destroy_gui_c
#define i_NUM_USERS i_NUM_USERS_gui_c
#define i_DEFAULT_FONT i_DEFAULT_FONT_gui_c
#define i_OnExit i_OnExit_gui_c
#include XSTR(NAPPGUI_SRC/gui/gui.c)
#undef _icon_t
#undef icon_t
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef func_destroy
#undef i_NUM_USERS
#undef i_DEFAULT_FONT
#undef i_OnExit
#endif // SKIP_GUI_C

#ifndef SKIP_EDITIMP_C
#define i_create i_create_editimp_c
#include XSTR(NAPPGUI_SRC/gui/editimp.c)
#undef i_create
#endif // SKIP_EDITIMP_C

#ifndef SKIP_GLOBALS_C
#include XSTR(NAPPGUI_SRC/gui/globals.c)
#endif // SKIP_GLOBALS_C

#ifndef SKIP_PANEL_C
#define i_create i_create_panel_c
#include XSTR(NAPPGUI_SRC/gui/panel.c)
#undef i_create
#endif // SKIP_PANEL_C

#ifndef SKIP_PROGRESS_C
#define i_create i_create_progress_c
#include XSTR(NAPPGUI_SRC/gui/progress.c)
#undef i_create
#endif // SKIP_PROGRESS_C

#ifndef SKIP_LABEL_C
#define i_OnDraw i_OnDraw_label_c
#define i_OnEnter i_OnEnter_label_c
#define i_OnExit i_OnExit_label_c
#define i_OnClick i_OnClick_label_c
#define i_OnAcceptFocus i_OnAcceptFocus_label_c
#define i_destroy_data i_destroy_data_label_c
#define i_create_data i_create_data_label_c
#include XSTR(NAPPGUI_SRC/gui/label.c)
#undef i_OnDraw
#undef i_OnEnter
#undef i_OnExit
#undef i_OnClick
#undef i_OnAcceptFocus
#undef i_destroy_data
#undef i_create_data
#endif // SKIP_LABEL_C

#ifndef SKIP_COMWIN_C
#include XSTR(NAPPGUI_SRC/gui/comwin.c)
#endif // SKIP_COMWIN_C

#ifndef SKIP_MENU_C
#define i_destroy i_destroy_menu_c
#include XSTR(NAPPGUI_SRC/gui/menu.c)
#undef i_destroy
#endif // SKIP_MENU_C

#ifndef SKIP_LISTBOX_C
#define _pelem_t _pelem_t_listbox_c
#define PElem PElem_listbox_c
#define i_OnDraw i_OnDraw_listbox_c
#define i_OnSize i_OnSize_listbox_c
#define i_OnEnter i_OnEnter_listbox_c
#define i_OnExit i_OnExit_listbox_c
#define i_OnMoved i_OnMoved_listbox_c
#define i_OnFocus i_OnFocus_listbox_c
#define i_OnDown i_OnDown_listbox_c
#define i_OnUp i_OnUp_listbox_c
#define i_OnKeyDown i_OnKeyDown_listbox_c
#define i_OnKeyUp i_OnKeyUp_listbox_c
#define i_destroy_data i_destroy_data_listbox_c
#define i_set_empty i_set_empty_listbox_c
#define arrst_PElem_create arrst_PElem_create_listbox_c
#define func_copy func_copy_listbox_c
#define func_read func_read_listbox_c
#define arrst_PElem_read_ex arrst_PElem_read_ex_listbox_c
#define func_remove func_remove_listbox_c
#define func_write func_write_listbox_c
#define arrst_PElem_write_ex arrst_PElem_write_ex_listbox_c
#define arrst_PElem_size arrst_PElem_size_listbox_c
#define arrst_PElem_get arrst_PElem_get_listbox_c
#define arrst_PElem_get_const arrst_PElem_get_const_listbox_c
#define arrst_PElem_last arrst_PElem_last_listbox_c
#define arrst_PElem_last_const arrst_PElem_last_const_listbox_c
#define arrst_PElem_all arrst_PElem_all_listbox_c
#define arrst_PElem_all_const arrst_PElem_all_const_listbox_c
#define arrst_PElem_insert arrst_PElem_insert_listbox_c
#define arrst_PElem_insert0 arrst_PElem_insert0_listbox_c
#define func_compare func_compare_listbox_c
#define arrst_PElem_sort_ex arrst_PElem_sort_ex_listbox_c
#define arrst_PElem_search arrst_PElem_search_listbox_c
#define arrst_PElem_search_const arrst_PElem_search_const_listbox_c
#define arrst_PElem_bsearch arrst_PElem_bsearch_listbox_c
#define arrst_PElem_bsearch_const arrst_PElem_bsearch_const_listbox_c
#define setst_PElem_create setst_PElem_create_listbox_c
#define setst_PElem_size setst_PElem_size_listbox_c
#define setst_PElem_get setst_PElem_get_listbox_c
#define setst_PElem_get_const setst_PElem_get_const_listbox_c
#define setst_PElem_first setst_PElem_first_listbox_c
#define setst_PElem_first_const setst_PElem_first_const_listbox_c
#define setst_PElem_last setst_PElem_last_listbox_c
#define setst_PElem_last_const setst_PElem_last_const_listbox_c
#define setst_PElem_next setst_PElem_next_listbox_c
#define setst_PElem_next_const setst_PElem_next_const_listbox_c
#define setst_PElem_prev setst_PElem_prev_listbox_c
#define setst_PElem_prev_const setst_PElem_prev_const_listbox_c
#define i_BOTTOM_PADDING i_BOTTOM_PADDING_listbox_c
#define i_create_data i_create_data_listbox_c
#define i_remove_elem i_remove_elem_listbox_c
#define i_document_size i_document_size_listbox_c
#define i_select i_select_listbox_c
#define i_update_sel_top i_update_sel_top_listbox_c
#define i_update_sel_bottom i_update_sel_bottom_listbox_c
#include XSTR(NAPPGUI_SRC/gui/listbox.c)
#undef _pelem_t
#undef PElem
#undef i_OnDraw
#undef i_OnSize
#undef i_OnEnter
#undef i_OnExit
#undef i_OnMoved
#undef i_OnFocus
#undef i_OnDown
#undef i_OnUp
#undef i_OnKeyDown
#undef i_OnKeyUp
#undef i_destroy_data
#undef i_set_empty
#undef arrst_PElem_create
#undef func_copy
#undef func_read
#undef arrst_PElem_read_ex
#undef func_remove
#undef func_write
#undef arrst_PElem_write_ex
#undef arrst_PElem_size
#undef arrst_PElem_get
#undef arrst_PElem_get_const
#undef arrst_PElem_last
#undef arrst_PElem_last_const
#undef arrst_PElem_all
#undef arrst_PElem_all_const
#undef arrst_PElem_insert
#undef arrst_PElem_insert0
#undef func_compare
#undef arrst_PElem_sort_ex
#undef arrst_PElem_search
#undef arrst_PElem_search_const
#undef arrst_PElem_bsearch
#undef arrst_PElem_bsearch_const
#undef setst_PElem_create
#undef setst_PElem_size
#undef setst_PElem_get
#undef setst_PElem_get_const
#undef setst_PElem_first
#undef setst_PElem_first_const
#undef setst_PElem_last
#undef setst_PElem_last_const
#undef setst_PElem_next
#undef setst_PElem_next_const
#undef setst_PElem_prev
#undef setst_PElem_prev_const
#undef i_BOTTOM_PADDING
#undef i_create_data
#undef i_remove_elem
#undef i_document_size
#undef i_select
#undef i_update_sel_top
#undef i_update_sel_bottom
#endif // SKIP_LISTBOX_C

#ifndef SKIP_RES_GUI_C
#include XSTR(NAPPGUI_SRC/gui/res_gui.c)
#endif // SKIP_RES_GUI_C

#ifndef SKIP_SPLITVIEW_C
#define i_OnDrag i_OnDrag_splitview_c
#define i_create i_create_splitview_c
#include XSTR(NAPPGUI_SRC/gui/splitview.c)
#undef i_OnDrag
#undef i_create
#endif // SKIP_SPLITVIEW_C

#ifndef SKIP_BUTTON_C
#define i_OnClick i_OnClick_button_c
#define i_create i_create_button_c
#define i_update_text i_update_text_button_c
#include XSTR(NAPPGUI_SRC/gui/button.c)
#undef i_OnClick
#undef i_create
#undef i_update_text
#endif // SKIP_BUTTON_C

#ifndef SKIP_DRAWCTRL_C
#define kCHECK_WIDTH kCHECK_WIDTH_drawctrl_c
#define kCHECK_HEIGHT kCHECK_HEIGHT_drawctrl_c
#include XSTR(NAPPGUI_SRC/gui/drawctrl.c)
#undef kCHECK_WIDTH
#undef kCHECK_HEIGHT
#endif // SKIP_DRAWCTRL_C

#ifndef SKIP_GUICONTROL_C
#include XSTR(NAPPGUI_SRC/gui/guicontrol.c)
#endif // SKIP_GUICONTROL_C

#ifndef SKIP_VIEW_C
#define i_OnDraw i_OnDraw_view_c
#define i_OnOverlay i_OnOverlay_view_c
#define i_OnEnter i_OnEnter_view_c
#define i_OnExit i_OnExit_view_c
#define i_OnMoved i_OnMoved_view_c
#define i_OnDown i_OnDown_view_c
#define i_OnUp i_OnUp_view_c
#define i_OnClick i_OnClick_view_c
#define i_OnDrag i_OnDrag_view_c
#define i_OnWheel i_OnWheel_view_c
#define i_OnKeyDown i_OnKeyDown_view_c
#define i_OnKeyUp i_OnKeyUp_view_c
#define i_OnFocus i_OnFocus_view_c
#define i_OnAcceptFocus i_OnAcceptFocus_view_c
#define i_OnScroll i_OnScroll_view_c
#define i_create i_create_view_c
#define i_destroy_data i_destroy_data_view_c
#include XSTR(NAPPGUI_SRC/gui/view.c)
#undef i_OnDraw
#undef i_OnOverlay
#undef i_OnEnter
#undef i_OnExit
#undef i_OnMoved
#undef i_OnDown
#undef i_OnUp
#undef i_OnClick
#undef i_OnDrag
#undef i_OnWheel
#undef i_OnKeyDown
#undef i_OnKeyUp
#undef i_OnFocus
#undef i_OnAcceptFocus
#undef i_OnScroll
#undef i_create
#undef i_destroy_data
#endif // SKIP_VIEW_C

#ifndef SKIP_WEBVIEW_C
#define i_OnFocus i_OnFocus_webview_c
#include XSTR(NAPPGUI_SRC/gui/webview.c)
#undef i_OnFocus
#endif // SKIP_WEBVIEW_C

#ifndef SKIP_ITEMS_C
#define _pelem_t _pelem_t_items_c
#define PElem PElem_items_c
#define arrst_PElem_create arrst_PElem_create_items_c
#define func_copy func_copy_items_c
#define func_read func_read_items_c
#define arrst_PElem_read_ex arrst_PElem_read_ex_items_c
#define func_remove func_remove_items_c
#define func_write func_write_items_c
#define arrst_PElem_write_ex arrst_PElem_write_ex_items_c
#define arrst_PElem_size arrst_PElem_size_items_c
#define arrst_PElem_get arrst_PElem_get_items_c
#define arrst_PElem_get_const arrst_PElem_get_const_items_c
#define arrst_PElem_last arrst_PElem_last_items_c
#define arrst_PElem_last_const arrst_PElem_last_const_items_c
#define arrst_PElem_all arrst_PElem_all_items_c
#define arrst_PElem_all_const arrst_PElem_all_const_items_c
#define arrst_PElem_insert arrst_PElem_insert_items_c
#define arrst_PElem_insert0 arrst_PElem_insert0_items_c
#define func_compare func_compare_items_c
#define arrst_PElem_sort_ex arrst_PElem_sort_ex_items_c
#define arrst_PElem_search arrst_PElem_search_items_c
#define arrst_PElem_search_const arrst_PElem_search_const_items_c
#define arrst_PElem_bsearch arrst_PElem_bsearch_items_c
#define arrst_PElem_bsearch_const arrst_PElem_bsearch_const_items_c
#define setst_PElem_create setst_PElem_create_items_c
#define setst_PElem_size setst_PElem_size_items_c
#define setst_PElem_get setst_PElem_get_items_c
#define setst_PElem_get_const setst_PElem_get_const_items_c
#define setst_PElem_first setst_PElem_first_items_c
#define setst_PElem_first_const setst_PElem_first_const_items_c
#define setst_PElem_last setst_PElem_last_items_c
#define setst_PElem_last_const setst_PElem_last_const_items_c
#define setst_PElem_next setst_PElem_next_items_c
#define setst_PElem_next_const setst_PElem_next_const_items_c
#define setst_PElem_prev setst_PElem_prev_items_c
#define setst_PElem_prev_const setst_PElem_prev_const_items_c
#define i_remove_elem i_remove_elem_items_c
#define i_create i_create_items_c
#include XSTR(NAPPGUI_SRC/gui/items.c)
#undef _pelem_t
#undef PElem
#undef arrst_PElem_create
#undef func_copy
#undef func_read
#undef arrst_PElem_read_ex
#undef func_remove
#undef func_write
#undef arrst_PElem_write_ex
#undef arrst_PElem_size
#undef arrst_PElem_get
#undef arrst_PElem_get_const
#undef arrst_PElem_last
#undef arrst_PElem_last_const
#undef arrst_PElem_all
#undef arrst_PElem_all_const
#undef arrst_PElem_insert
#undef arrst_PElem_insert0
#undef func_compare
#undef arrst_PElem_sort_ex
#undef arrst_PElem_search
#undef arrst_PElem_search_const
#undef arrst_PElem_bsearch
#undef arrst_PElem_bsearch_const
#undef setst_PElem_create
#undef setst_PElem_size
#undef setst_PElem_get
#undef setst_PElem_get_const
#undef setst_PElem_first
#undef setst_PElem_first_const
#undef setst_PElem_last
#undef setst_PElem_last_const
#undef setst_PElem_next
#undef setst_PElem_next_const
#undef setst_PElem_prev
#undef setst_PElem_prev_const
#undef i_remove_elem
#undef i_create
#endif // SKIP_ITEMS_C

#ifndef SKIP_COMPONENT_C
#include XSTR(NAPPGUI_SRC/gui/component.c)
#endif // SKIP_COMPONENT_C

#ifndef SKIP_MENUITEM_C
#define i_create i_create_menuitem_c
#define i_update_text i_update_text_menuitem_c
#include XSTR(NAPPGUI_SRC/gui/menuitem.c)
#undef i_create
#undef i_update_text
#endif // SKIP_MENUITEM_C

#ifndef SKIP_TEXTVIEW_C
#define i_OnFilter i_OnFilter_textview_c
#define i_OnFocus i_OnFocus_textview_c
#include XSTR(NAPPGUI_SRC/gui/textview.c)
#undef i_OnFilter
#undef i_OnFocus
#endif // SKIP_TEXTVIEW_C

#ifndef SKIP_LAYOUT_C
#define _ctype_t _ctype_t_layout_c
#define ctype_t ctype_t_layout_c
#define func_copy func_copy_layout_c
#define func_read func_read_layout_c
#define func_remove func_remove_layout_c
#define func_write func_write_layout_c
#define func_compare func_compare_layout_c
#define i_EPSILON i_EPSILON_layout_c
#include XSTR(NAPPGUI_SRC/gui/layout.c)
#undef _ctype_t
#undef ctype_t
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_EPSILON
#endif // SKIP_LAYOUT_C

#ifndef SKIP_OSSLIDER_C
#include XSTR(NAPPGUI_SRC/osgui/osslider.c)
#endif // SKIP_OSSLIDER_C

#ifndef SKIP_OSSLIDER_C
#define i_OnMoved i_OnMoved_osslider_c
#define i_OnPressed i_OnPressed_osslider_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osslider.c)
#undef i_OnMoved
#undef i_OnPressed
#endif // SKIP_OSSLIDER_C

#ifndef SKIP_OSENTRY_C
#define i_iter i_iter_osentry_c
#define i_OnFilter i_OnFilter_osentry_c
#define i_OnBufferInsert i_OnBufferInsert_osentry_c
#define i_OnBufferDelete i_OnBufferDelete_osentry_c
#define i_create i_create_osentry_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osentry.c)
#undef i_iter
#undef i_OnFilter
#undef i_OnBufferInsert
#undef i_OnBufferDelete
#undef i_create
#endif // SKIP_OSENTRY_C

#ifndef SKIP_OSEDIT_C
#define i_OnDraw i_OnDraw_osedit_c
#define i_OnKeyPress i_OnKeyPress_osedit_c
#define i_OnPressed i_OnPressed_osedit_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osedit.c)
#undef i_OnDraw
#undef i_OnKeyPress
#undef i_OnPressed
#endif // SKIP_OSEDIT_C

#ifndef SKIP_OSUPDOWN_C
#define i_OnDraw i_OnDraw_osupdown_c
#define i_OnClick i_OnClick_osupdown_c
#define i_OnMove i_OnMove_osupdown_c
#define i_OnExit i_OnExit_osupdown_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osupdown.c)
#undef i_OnDraw
#undef i_OnClick
#undef i_OnMove
#undef i_OnExit
#endif // SKIP_OSUPDOWN_C

#ifndef SKIP_OSWEB_C
#define i_OnPressed i_OnPressed_osweb_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osweb.c)
#undef i_OnPressed
#endif // SKIP_OSWEB_C

#ifndef SKIP_OSSPLIT_C
#define func_copy func_copy_ossplit_c
#define func_read func_read_ossplit_c
#define func_destroy func_destroy_ossplit_c
#define func_write func_write_ossplit_c
#define func_compare func_compare_ossplit_c
#define i_OnMove i_OnMove_ossplit_c
#define i_OnPressed i_OnPressed_ossplit_c
#define i_OnRelease i_OnRelease_ossplit_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/ossplit.c)
#undef func_copy
#undef func_read
#undef func_destroy
#undef func_write
#undef func_compare
#undef i_OnMove
#undef i_OnPressed
#undef i_OnRelease
#endif // SKIP_OSSPLIT_C

#ifndef SKIP_OSVIEW_C
#define i_OnDraw i_OnDraw_osview_c
#define i_OnMove i_OnMove_osview_c
#define i_OnEnter i_OnEnter_osview_c
#define i_OnExit i_OnExit_osview_c
#define i_OnPressed i_OnPressed_osview_c
#define i_OnRelease i_OnRelease_osview_c
#define i_OnWheel i_OnWheel_osview_c
#define i_OnKeyPress i_OnKeyPress_osview_c
#define i_OnKeyRelease i_OnKeyRelease_osview_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osview.c)
#undef i_OnDraw
#undef i_OnMove
#undef i_OnEnter
#undef i_OnExit
#undef i_OnPressed
#undef i_OnRelease
#undef i_OnWheel
#undef i_OnKeyPress
#undef i_OnKeyRelease
#endif // SKIP_OSVIEW_C

#ifndef SKIP_OSMENUITEM_C
#define i_OnClick i_OnClick_osmenuitem_c
#define i_destroy_widget i_destroy_widget_osmenuitem_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osmenuitem.c)
#undef i_OnClick
#undef i_destroy_widget
#endif // SKIP_OSMENUITEM_C

#ifndef SKIP_OSGLOBALS_C
#define kCHECK_WIDTH kCHECK_WIDTH_osglobals_c
#define kCHECK_HEIGHT kCHECK_HEIGHT_osglobals_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osglobals.c)
#undef kCHECK_WIDTH
#undef kCHECK_HEIGHT
#endif // SKIP_OSGLOBALS_C

#ifndef SKIP_OSWINDOW_C
#define i_OnKeyPress i_OnKeyPress_oswindow_c
#define i_OnKeyRelease i_OnKeyRelease_oswindow_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/oswindow.c)
#undef i_OnKeyPress
#undef i_OnKeyRelease
#endif // SKIP_OSWINDOW_C

#ifndef SKIP_OSBUTTON_C
#define i_OnClick i_OnClick_osbutton_c
#define i_OnKeyPress i_OnKeyPress_osbutton_c
#define i_OnPressed i_OnPressed_osbutton_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osbutton.c)
#undef i_OnClick
#undef i_OnKeyPress
#undef i_OnPressed
#endif // SKIP_OSBUTTON_C

#ifndef SKIP_OSCONTROL_C
#define i_OnFocus i_OnFocus_oscontrol_c
#define i_align i_align_oscontrol_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/oscontrol.c)
#undef i_OnFocus
#undef i_align
#endif // SKIP_OSCONTROL_C

#ifndef SKIP_OSMENU_C
#define i_destroy_widget i_destroy_widget_osmenu_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osmenu.c)
#undef i_destroy_widget
#endif // SKIP_OSMENU_C

#ifndef SKIP_OSTEXT_C
#define i_PANGO_TO_PIXELS i_PANGO_TO_PIXELS_ostext_c
#define i_device_to_pixels i_device_to_pixels_ostext_c
#define i_OnPressed i_OnPressed_ostext_c
#define i_OnFilter i_OnFilter_ostext_c
#define i_OnBufferInsert i_OnBufferInsert_ostext_c
#define i_OnBufferDelete i_OnBufferDelete_ostext_c
#define i_iter i_iter_ostext_c
#define i_select i_select_ostext_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/ostext.c)
#undef i_PANGO_TO_PIXELS
#undef i_device_to_pixels
#undef i_OnPressed
#undef i_OnFilter
#undef i_OnBufferInsert
#undef i_OnBufferDelete
#undef i_iter
#undef i_select
#endif // SKIP_OSTEXT_C

#ifndef SKIP_OSSCROLL_C
#define i_OnRealize i_OnRealize_osscroll_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/osscroll.c)
#undef i_OnRealize
#endif // SKIP_OSSCROLL_C

#ifndef SKIP_OSPOPUP_C
#define i_OnSelect i_OnSelect_ospopup_c
#define i_OnPressed i_OnPressed_ospopup_c
#define i_OnEnter i_OnEnter_ospopup_c
#define i_OnLeave i_OnLeave_ospopup_c
#define i_img_dest i_img_dest_ospopup_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/ospopup.c)
#undef i_OnSelect
#undef i_OnPressed
#undef i_OnEnter
#undef i_OnLeave
#undef i_img_dest
#endif // SKIP_OSPOPUP_C

#ifndef SKIP_OSLISTENER_C
#include XSTR(NAPPGUI_SRC/osgui/gtk/oslistener.c)
#endif // SKIP_OSLISTENER_C

#ifndef SKIP_OSDRAWCTRL_C
#include XSTR(NAPPGUI_SRC/osgui/gtk/osdrawctrl.c)
#endif // SKIP_OSDRAWCTRL_C

#ifndef SKIP_OSCOMBO_C
#define i_OnPressed i_OnPressed_oscombo_c
#define i_OnMove i_OnMove_oscombo_c
#define i_OnEnter i_OnEnter_oscombo_c
#define i_OnLeave i_OnLeave_oscombo_c
#define i_OnSelect i_OnSelect_oscombo_c
#define i_img_dest i_img_dest_oscombo_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/oscombo.c)
#undef i_OnPressed
#undef i_OnMove
#undef i_OnEnter
#undef i_OnLeave
#undef i_OnSelect
#undef i_img_dest
#endif // SKIP_OSCOMBO_C

#ifndef SKIP_OSPANEL_C
#define func_copy func_copy_ospanel_c
#define func_read func_read_ospanel_c
#define func_remove func_remove_ospanel_c
#define func_write func_write_ospanel_c
#define func_compare func_compare_ospanel_c
#define i_OnDraw i_OnDraw_ospanel_c
#define i_OnPressed i_OnPressed_ospanel_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/ospanel.c)
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef i_OnDraw
#undef i_OnPressed
#endif // SKIP_OSPANEL_C

#ifndef SKIP_OSCOMWIN_C
#define i_OnRealize i_OnRealize_oscomwin_c
#include XSTR(NAPPGUI_SRC/osgui/gtk/oscomwin.c)
#undef i_OnRealize
#endif // SKIP_OSCOMWIN_C

#ifndef SKIP_OSGUI_GTK_C
#include XSTR(NAPPGUI_SRC/osgui/gtk/osgui_gtk.c)
#endif // SKIP_OSGUI_GTK_C

#ifndef SKIP_OSPROGRESS_C
#include XSTR(NAPPGUI_SRC/osgui/gtk/osprogress.c)
#endif // SKIP_OSPROGRESS_C

#ifndef SKIP_OSSCROLLS_C
#include XSTR(NAPPGUI_SRC/osgui/osscrolls.c)
#endif // SKIP_OSSCROLLS_C

#ifndef SKIP_OSEDIT_C
#include XSTR(NAPPGUI_SRC/osgui/osedit.c)
#endif // SKIP_OSEDIT_C

#ifndef SKIP_OSUPDOWN_C
#include XSTR(NAPPGUI_SRC/osgui/osupdown.c)
#endif // SKIP_OSUPDOWN_C

#ifndef SKIP_OSWEB_C
#include XSTR(NAPPGUI_SRC/osgui/osweb.c)
#endif // SKIP_OSWEB_C

#ifndef SKIP_OSSPLIT_C
#include XSTR(NAPPGUI_SRC/osgui/ossplit.c)
#endif // SKIP_OSSPLIT_C

#ifndef SKIP_OSGUICTX_C
#include XSTR(NAPPGUI_SRC/osgui/osguictx.c)
#endif // SKIP_OSGUICTX_C

#ifndef SKIP_OSVIEW_C
#include XSTR(NAPPGUI_SRC/osgui/osview.c)
#endif // SKIP_OSVIEW_C

#ifndef SKIP_OSWINDOW_C
#include XSTR(NAPPGUI_SRC/osgui/oswindow.c)
#endif // SKIP_OSWINDOW_C

#ifndef SKIP_OSBUTTON_C
#include XSTR(NAPPGUI_SRC/osgui/osbutton.c)
#endif // SKIP_OSBUTTON_C

#ifndef SKIP_OSCONTROL_C
#include XSTR(NAPPGUI_SRC/osgui/oscontrol.c)
#endif // SKIP_OSCONTROL_C

#ifndef SKIP_OSTEXT_C
#include XSTR(NAPPGUI_SRC/osgui/ostext.c)
#endif // SKIP_OSTEXT_C

#ifndef SKIP_OSGUI_C
#define i_NUM_USERS i_NUM_USERS_osgui_c
#define i_DEFAULT_FONT i_DEFAULT_FONT_osgui_c
#include XSTR(NAPPGUI_SRC/osgui/osgui.c)
#undef i_NUM_USERS
#undef i_DEFAULT_FONT
#endif // SKIP_OSGUI_C

#ifndef SKIP_OSPOPUP_C
#include XSTR(NAPPGUI_SRC/osgui/ospopup.c)
#endif // SKIP_OSPOPUP_C

#ifndef SKIP_OSCOMBO_C
#include XSTR(NAPPGUI_SRC/osgui/oscombo.c)
#endif // SKIP_OSCOMBO_C

#ifndef SKIP_OSPANEL_C
#include XSTR(NAPPGUI_SRC/osgui/ospanel.c)
#endif // SKIP_OSPANEL_C

#ifndef SKIP_OSTABSTOP_C
#include XSTR(NAPPGUI_SRC/osgui/ostabstop.c)
#endif // SKIP_OSTABSTOP_C

#ifndef SKIP_OSPROGRESS_C
#include XSTR(NAPPGUI_SRC/osgui/osprogress.c)
#endif // SKIP_OSPROGRESS_C

#ifndef SKIP_JSON_C
#define i_write_container i_write_container_json_c
#define i_write_binary i_write_binary_json_c
#include XSTR(NAPPGUI_SRC/encode/json.c)
#undef i_write_container
#undef i_write_binary
#endif // SKIP_JSON_C

#ifndef SKIP_ENCODE_C
#define i_NUM_USERS i_NUM_USERS_encode_c
#include XSTR(NAPPGUI_SRC/encode/encode.c)
#undef i_NUM_USERS
#endif // SKIP_ENCODE_C

#ifndef SKIP_BASE64_C
#include XSTR(NAPPGUI_SRC/encode/base64.c)
#endif // SKIP_BASE64_C

#ifndef SKIP_URL_C
#include XSTR(NAPPGUI_SRC/encode/url.c)
#endif // SKIP_URL_C

#ifndef SKIP_OSAPP_GTK_C
#define i_terminate i_terminate_osapp_gtk_c
#include XSTR(NAPPGUI_SRC/osapp/gtk/osapp_gtk.c)
#undef i_terminate
#endif // SKIP_OSAPP_GTK_C

#ifndef SKIP_OSAPP_C
#define _icon_t _icon_t_osapp_c
#define icon_t icon_t_osapp_c
#define func_copy func_copy_osapp_c
#define func_read func_read_osapp_c
#define func_remove func_remove_osapp_c
#define func_write func_write_osapp_c
#define func_compare func_compare_osapp_c
#define func_destroy func_destroy_osapp_c
#define i_terminate i_terminate_osapp_c
#include XSTR(NAPPGUI_SRC/osapp/osapp.c)
#undef _icon_t
#undef icon_t
#undef func_copy
#undef func_read
#undef func_remove
#undef func_write
#undef func_compare
#undef func_destroy
#undef i_terminate
#endif // SKIP_OSAPP_C

