// Autogenerated by gen_jumbo.c

#include "conf.h"

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#ifndef SKIP_CORE_CPP
#define i_NUM_USERS i_NUM_USERS_core_cpp
#include XSTR(NAPPGUI_SRC/core/core.cpp)
#undef i_NUM_USERS
#endif // SKIP_CORE_CPP

#ifndef SKIP_EVENT_CPP
#include XSTR(NAPPGUI_SRC/core/event.cpp)
#endif // SKIP_EVENT_CPP

#ifndef SKIP_DRAWG_CPP
#include XSTR(NAPPGUI_SRC/draw2d/drawg.cpp)
#endif // SKIP_DRAWG_CPP

#ifndef SKIP_CIR2D_CPP
#define i_from_points i_from_points_cir2d_cpp
#define i_area i_area_cir2d_cpp
#define i_is_null i_is_null_cir2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/cir2d.cpp)
#undef i_from_points
#undef i_area
#undef i_is_null
#endif // SKIP_CIR2D_CPP

#ifndef SKIP_S2D_CPP
#include XSTR(NAPPGUI_SRC/geom2d/s2d.cpp)
#endif // SKIP_S2D_CPP

#ifndef SKIP_POL2D_CPP
#define i_create i_create_pol2d_cpp
#define i_ccw i_ccw_pol2d_cpp
#define i_dist i_dist_pol2d_cpp
#define i_copy i_copy_pol2d_cpp
#define i_destroy i_destroy_pol2d_cpp
#define i_transform i_transform_pol2d_cpp
#define i_area i_area_pol2d_cpp
#define i_box i_box_pol2d_cpp
#define i_centroid i_centroid_pol2d_cpp
#define i_sat_poly i_sat_poly_pol2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/pol2d.cpp)
#undef i_create
#undef i_ccw
#undef i_dist
#undef i_copy
#undef i_destroy
#undef i_transform
#undef i_area
#undef i_box
#undef i_centroid
#undef i_sat_poly
#endif // SKIP_POL2D_CPP

#ifndef SKIP_V2D_CPP
#define i_add i_add_v2d_cpp
#define i_length i_length_v2d_cpp
#define i_sqlength i_sqlength_v2d_cpp
#define i_dist i_dist_v2d_cpp
#define i_sqdist i_sqdist_v2d_cpp
#define i_angle i_angle_v2d_cpp
#define i_rotate i_rotate_v2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/v2d.cpp)
#undef i_add
#undef i_length
#undef i_sqlength
#undef i_dist
#undef i_sqdist
#undef i_angle
#undef i_rotate
#endif // SKIP_V2D_CPP

#ifndef SKIP_POLABEL_CPP
#define i_init_cell i_init_cell_polabel_cpp
#include XSTR(NAPPGUI_SRC/geom2d/polabel.cpp)
#undef i_init_cell
#endif // SKIP_POLABEL_CPP

#ifndef SKIP_T2D_CPP
#define i_move i_move_t2d_cpp
#define i_rotate i_rotate_t2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/t2d.cpp)
#undef i_move
#undef i_rotate
#endif // SKIP_T2D_CPP

#ifndef SKIP_OBB2D_CPP
#define i_create i_create_obb2d_cpp
#define i_from_points i_from_points_obb2d_cpp
#define i_copy i_copy_obb2d_cpp
#define i_destroy i_destroy_obb2d_cpp
#define i_move i_move_obb2d_cpp
#define i_transform i_transform_obb2d_cpp
#define i_sat_poly i_sat_poly_obb2d_cpp
#define i_center i_center_obb2d_cpp
#define i_width i_width_obb2d_cpp
#define i_height i_height_obb2d_cpp
#define i_angle i_angle_obb2d_cpp
#define i_area i_area_obb2d_cpp
#define i_box i_box_obb2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/obb2d.cpp)
#undef i_create
#undef i_from_points
#undef i_copy
#undef i_destroy
#undef i_move
#undef i_transform
#undef i_sat_poly
#undef i_center
#undef i_width
#undef i_height
#undef i_angle
#undef i_area
#undef i_box
#endif // SKIP_OBB2D_CPP

#ifndef SKIP_R2D_CPP
#define i_center i_center_r2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/r2d.cpp)
#undef i_center
#endif // SKIP_R2D_CPP

#ifndef SKIP_TRI2D_CPP
#define i_transform i_transform_tri2d_cpp
#define i_area i_area_tri2d_cpp
#define i_ccw i_ccw_tri2d_cpp
#define i_centroid i_centroid_tri2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/tri2d.cpp)
#undef i_transform
#undef i_area
#undef i_ccw
#undef i_centroid
#endif // SKIP_TRI2D_CPP

#ifndef SKIP_COL2D_CPP
#define i_create i_create_col2d_cpp
#define i_copy i_copy_col2d_cpp
#define i_destroy i_destroy_col2d_cpp
#define i_limits i_limits_col2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/col2d.cpp)
#undef i_create
#undef i_copy
#undef i_destroy
#undef i_limits
#endif // SKIP_COL2D_CPP

#ifndef SKIP_POLPART_CPP
#include XSTR(NAPPGUI_SRC/geom2d/polpart.cpp)
#endif // SKIP_POLPART_CPP

#ifndef SKIP_SEG2D_CPP
#define i_length i_length_seg2d_cpp
#define i_sqlength i_sqlength_seg2d_cpp
#define i_sqdist i_sqdist_seg2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/seg2d.cpp)
#undef i_length
#undef i_sqlength
#undef i_sqdist
#endif // SKIP_SEG2D_CPP

#ifndef SKIP_BOX2D_CPP
#define i_add i_add_box2d_cpp
#define i_from_points i_from_points_box2d_cpp
#define i_center i_center_box2d_cpp
#define i_is_null i_is_null_box2d_cpp
#define i_area i_area_box2d_cpp
#include XSTR(NAPPGUI_SRC/geom2d/box2d.cpp)
#undef i_add
#undef i_from_points
#undef i_center
#undef i_is_null
#undef i_area
#endif // SKIP_BOX2D_CPP

#ifndef SKIP_BMATH_CPP
#include XSTR(NAPPGUI_SRC/sewer/bmath.cpp)
#endif // SKIP_BMATH_CPP

