// Autogenerated by gen_inc.c

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#undef linux
#include XSTR(GLIB_CONF_H_DIR/glibconfig.h)
#define linux 1
