// Autogenerated by gen_inc.c

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#include XSTR(HARFBUZZ_H_DIR/hb-features.h)

