// AUTOGENERATED

// Optional manual x macros
#ifndef FOR_MANUAL_WINDOWS_C_FUNCS_DO
#define FOR_MANUAL_WINDOWS_C_FUNCS_DO(C_MACRO)
#endif

// Delay macro application to allow all the dumb WS() name macros to expand.
#define DELAY(MACRO, ...) MACRO(__VA_ARGS__)

#define FOR_WINDOWS_C_FUNCS_DO(C_MACRO) \
    C_MACRO(WINBASEAPI HLOCAL WINAPI, LocalFree, (HLOCAL a), (a), LocalFree, KernelBase, KernelBase,return)\
    C_MACRO(BOOLAPI, InternetCloseHandle, (HINTERNET a), (a), InternetCloseHandle, wininet, wininet,return)\
    C_MACRO(_ACRTIMP double __cdecl, log, (double a), (a), log, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetFileSizeEx, (HANDLE a, PLARGE_INTEGER b), (a, b), GetFileSizeEx, KernelBase, KernelBase,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, GetModuleFileNameW, (HMODULE a, LPWSTR b, DWORD c), (a, b, c), GetModuleFileNameW, KernelBase, KernelBase,return)\
    C_MACRO(WINGDIAPI HBRUSH WINAPI, CreatePatternBrush, (HBITMAP a), (a), CreatePatternBrush, gdi32full, gdi32full,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, CreatePipe, (PHANDLE a, PHANDLE b, LPSECURITY_ATTRIBUTES c, DWORD d), (a, b, c, d), CreatePipe, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI INT WINAPI, TranslateAcceleratorW, (HWND a, HACCEL b, LPMSG c), (a, b, c), TranslateAcceleratorW, user32, user32,return)\
    C_MACRO(WGLAPI PROC WINAPI, wglGetProcAddress, (LPCSTR a), (a), wglGetProcAddress, opengl32, opengl32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipResetWorldTransform, (GpGraphics* a), (a), GdipResetWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateFromHDC, (HDC a, GpGraphics** b), (a, b), GdipCreateFromHDC, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, IsDebuggerPresent, (), (), IsDebuggerPresent, IumSdk, IumSdk,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetSolidFillColor, (GpSolidFill* a, ARGB b), (a, b), GdipSetSolidFillColor, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI LONG_PTR WINAPI, GetWindowLongPtrW, (HWND a, INT b), (a, b), GetWindowLongPtrW, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, TerminateProcess, (HANDLE a, DWORD b), (a, b), TerminateProcess, IumSdk, IumSdk,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetTextureTransform, (GpTexture * a, GDIPCONST GpMatrix* b), (a, b), GdipSetTextureTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, SetActiveWindow, (HWND a), (a), SetActiveWindow, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(getsockname), (SOCKET a, struct WS(sockaddr) * b, int * c), (a, b, c), getsockname, ws2_32, ws2_32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImageWidth, (GpImage* a, UINT* b), (a, b), GdipGetImageWidth, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI HANDLE WINAPI, FindFirstFileW, (LPCWSTR a, LPWIN32_FIND_DATAW b), (a, b), FindFirstFileW, KernelBase, KernelBase,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, FindNextFileW, (HANDLE a, LPWIN32_FIND_DATAW b), (a, b), FindNextFileW, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ReleaseCapture, (), (), ReleaseCapture, user32, user32,return)\
    C_MACRO(WINBASEAPI void WINAPI, DebugBreak, (), (), DebugBreak, IumSdk, IumSdk,)\
    C_MACRO(WINUSERAPI HMENU WINAPI, CreatePopupMenu, (), (), CreatePopupMenu, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DestroyIcon, (HICON a), (a), DestroyIcon, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenLineJoin, (GpPen* a, GpLineJoin b), (a, b), GdipSetPenLineJoin, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI INT WINAPI, GetMenuItemCount, (HMENU a), (a), GetMenuItemCount, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetFileTime, (HANDLE a, LPFILETIME b, LPFILETIME c, LPFILETIME d), (a, b, c, d), GetFileTime, KernelBase, KernelBase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImageGraphicsContext, (GpImage* a, GpGraphics** b), (a, b), GdipGetImageGraphicsContext, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateBitmapFromStream, (IStream* a, GpBitmap** b), (a, b), GdipCreateBitmapFromStream, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI VOID WINAPI, GetLocalTime, (LPSYSTEMTIME a), (a), GetLocalTime, IumSdk, IumSdk,)\
    C_MACRO(_ACRTIMP void __cdecl, _aligned_free, (void* a), (a), _aligned_free, ucrtbase_clr0400, ucrtbase_clr0400,)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImageHeight, (GpImage* a, UINT* b), (a, b), GdipGetImageHeight, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, SetCapture, (HWND a), (a), SetCapture, user32, user32,return)\
    C_MACRO(_ACRTIMP void __cdecl, free, (void* a), (a), free, ucrtbase_clr0400, ucrtbase_clr0400,)\
    C_MACRO(WINGDIAPI HBRUSH WINAPI, CreateSolidBrush, (COLORREF a), (a), CreateSolidBrush, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI HMENU WINAPI, GetMenu, (HWND a), (a), GetMenu, user32, user32,return)\
    C_MACRO(WINGDIAPI COLORREF WINAPI, SetTextColor, (HDC a, COLORREF b), (a, b), SetTextColor, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, EnumChildWindows, (HWND a, WNDENUMPROC b, LPARAM c), (a, b, c), EnumChildWindows, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipImageSelectActiveFrame, (GpImage* a, GDIPCONST GUID* b, UINT c), (a, b, c), GdipImageSelectActiveFrame, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP int __cdecl, isalpha, (int a), (a), isalpha, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DrawMenuBar, (HWND a), (a), DrawMenuBar, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPenDashStyle, (GpPen* a, GpDashStyle* b), (a, b), GdipGetPenDashStyle, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI HPEN WINAPI, CreatePen, (INT a, INT b, COLORREF c), (a, b, c), CreatePen, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI SHORT WINAPI, GetKeyState, (INT a), (a), GetKeyState, user32, user32,return)\
    C_MACRO(WGLAPI HGLRC WINAPI, wglCreateContext, (HDC a), (a), wglCreateContext, opengl32, opengl32,return)\
    C_MACRO(WINUSERAPI LRESULT WINAPI, DefWindowProcW, (HWND a, UINT b, WPARAM c, LPARAM d), (a, b, c, d), DefWindowProcW, user32, user32,return)\
    C_MACRO(WGLAPI HDC WINAPI, wglGetCurrentDC, (), (), wglGetCurrentDC, opengl32, opengl32,return)\
    C_MACRO(_ACRTIMP float __cdecl, sqrtf, (float a), (a), sqrtf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP DECLSPEC_NORETURN void __cdecl, exit, (int a), (a), exit, ucrtbase_clr0400, ucrtbase_clr0400,)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(listen), (SOCKET a, int b), (a, b), listen, ws2_32, ws2_32,return)\
    C_MACRO(_ACRTIMP double __cdecl, ceil, (double a), (a), ceil, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateFont, (GDIPCONST GpFontFamily* a, REAL b, INT c, Unit d, GpFont** e), (a, b, c, d, e), GdipCreateFont, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, GetLastError, (), (), GetLastError, IumSdk, IumSdk,return)\
    C_MACRO(WINSOCK_API_LINKAGE int WINAPI, WSAGetLastError, (), (), WSAGetLastError, ws2_32, ws2_32,return)\
    C_MACRO(_ACRTIMP char* __cdecl, strstr, (const char* a, const char* b), (a, b), strstr, ucrtbase, ucrtbase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipMeasureString, (GpGraphics* a, GDIPCONST WCHAR* b, INT c, GDIPCONST GpFont* d, GDIPCONST RectF* e, GDIPCONST GpStringFormat* f, RectF* g, INT* h, INT* i), (a, b, c, d, e, f, g, h, i), GdipMeasureString, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, MoveToEx, (HDC a, INT b, INT c, LPPOINT d), (a, b, c, d), MoveToEx, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP char* __cdecl, getenv, (const char* a), (a), getenv, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP DECLSPEC_NORETURN void __cdecl, abort, (), (), abort, ucrtbase_clr0400, ucrtbase_clr0400,)\
    C_MACRO(GpStatus WINGDIPAPI, GdipMultiplyWorldTransform, (GpGraphics* a, GDIPCONST GpMatrix* b, GpMatrixOrder c), (a, b, c), GdipMultiplyWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, GetTempPathW, (DWORD a, LPWSTR b), (a, b), GetTempPathW, KernelBase, KernelBase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipAddPathArcI, (GpPath* a, INT b, INT c, INT d, INT e, REAL f, REAL g), (a, b, c, d, e, f, g), GdipAddPathArcI, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipInvertMatrix, (GpMatrix* a), (a), GdipInvertMatrix, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, SetHandleInformation, (HANDLE a, DWORD b, DWORD c), (a, b, c), SetHandleInformation, KernelBase, KernelBase,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, SwapBuffers, (HDC a), (a), SwapBuffers, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SetRectEmpty, (LPRECT a), (a), SetRectEmpty, user32, user32,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, Rectangle, (HDC a, INT b, INT c, INT d, INT e), (a, b, c, d, e), Rectangle, gdi32full, gdi32full,return)\
    C_MACRO(WINSHELLAPI HRESULT WINAPI, SHGetFolderPathW, (HWND hwnd, int nFolder, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath), (hwnd, nFolder, hToken, dwFlags, pszPath), SHGetFolderPathW, windows.storage, windows_storage,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, TrackMouseEvent, (LPTRACKMOUSEEVENT a), (a), TrackMouseEvent, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenColor, (GpPen* a, ARGB b), (a, b), GdipSetPenColor, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP void* __cdecl, malloc, (size_t a), (a), malloc, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawBezier, (GpGraphics* a, GpPen* b, REAL c, REAL d, REAL e, REAL f, REAL g, REAL h, REAL i, REAL j), (a, b, c, d, e, f, g, h, i, j), GdipDrawBezier, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP __int64 __cdecl, _strtoi64, (const char* a, char** b, int c), (a, b, c), _strtoi64, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, LineTo, (HDC a, INT b, INT c), (a, b, c), LineTo, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DestroyCursor, (HCURSOR a), (a), DestroyCursor, user32, user32,return)\
    C_MACRO(WINUSERAPI HICON WINAPI, CreateIconIndirect, (PICONINFO a), (a), CreateIconIndirect, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetMatrixElements, (GpMatrix* a, REAL b, REAL c, REAL d, REAL e, REAL f, REAL g), (a, b, c, d, e, f, g), GdipSetMatrixElements, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI HANDLE WINAPI, CreateMutexW, (LPSECURITY_ATTRIBUTES a, BOOL b, LPCWSTR c), (a, b, c), CreateMutexW, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI INT WINAPI, ScrollWindowEx, (HWND a, INT b, INT c, const RECT* d, const RECT* e, HRGN f, LPRECT g, UINT h), (a, b, c, d, e, f, g, h), ScrollWindowEx, user32, user32,return)\
    C_MACRO(WINBASEAPI VOID DECLSPEC_NORETURN WINAPI, ExitProcess, (DWORD a), (a), ExitProcess, IumSdk, IumSdk,)\
    C_MACRO(INTERNETAPI HINTERNET WINAPI, InternetConnectW, (HINTERNET a, LPCWSTR b, INTERNET_PORT c, LPCWSTR d, LPCWSTR e, DWORD f, DWORD g, DWORD_PTR h), (a, b, c, d, e, f, g, h), InternetConnectW, wininet, wininet,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipImageGetFrameDimensionsList, (GpImage* a, GUID* b, UINT c), (a, b, c), GdipImageGetFrameDimensionsList, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI INT WINAPI, FillRect, (HDC a, const RECT* b, HBRUSH c), (a, b, c), FillRect, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawPath, (GpGraphics* a, GpPen* b, GpPath* c), (a, b, c), GdipDrawPath, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP double __cdecl, log10, (double a), (a), log10, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, CreateProcessW, (LPCWSTR a, LPWSTR b, LPSECURITY_ATTRIBUTES c, LPSECURITY_ATTRIBUTES d, BOOL e, DWORD f, LPVOID g, LPCWSTR h, LPSTARTUPINFOW i, LPPROCESS_INFORMATION j), (a, b, c, d, e, f, g, h, i, j), CreateProcessW, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI HDC WINAPI, GetWindowDC, (HWND a), (a), GetWindowDC, user32, user32,return)\
    C_MACRO(WINCOMMCTRLAPI BOOL WINAPI, ImageList_Destroy, (HIMAGELIST a), (a), ImageList_Destroy, comctl32, comctl32,return)\
    C_MACRO(WINBASEAPI HMODULE WINAPI, LoadLibraryW, (LPCWSTR a), (a), LoadLibraryW, KernelBase, KernelBase,return)\
    C_MACRO(WINGDIAPI HFONT WINAPI, CreateFontW, (INT a, INT b, INT c, INT d, INT e, DWORD f, DWORD g, DWORD h, DWORD i, DWORD j, DWORD k, DWORD l, DWORD m, LPCWSTR n), (a, b, c, d, e, f, g, h, i, j, k, l, m, n), CreateFontW, gdi32full, gdi32full,return)\
    C_MACRO(WINSHELLAPI HINSTANCE WINAPI, ShellExecuteW, (HWND a, LPCWSTR b, LPCWSTR c, LPCWSTR d, LPCWSTR e, INT f), (a, b, c, d, e, f), ShellExecuteW, windows.storage, windows_storage,return)\
    C_MACRO(_ACRTIMP double __cdecl, exp, (double a), (a), exp, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP float __cdecl, powf, (float a, float b), (a, b), powf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipAddPathLine, (GpPath* a, REAL b, REAL c, REAL d, REAL e), (a, b, c, d, e), GdipAddPathLine, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI DWORD WINAPI, GetDialogBaseUnits, (), (), GetDialogBaseUnits, user32, user32,return)\
    C_MACRO(_ACRTIMP float __cdecl, expf, (float a), (a), expf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP int* __cdecl, _errno, (), (), _errno, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImagePixelFormat, (GpImage* a, PixelFormat* b), (a, b), GdipGetImagePixelFormat, GdiPlus, GdiPlus,return)\
    C_MACRO(GLAPI void GLAPIENTRY, glGetIntegerv, (GLenum pname, GLint *params), (pname, params), glGetIntegerv, opengl32, opengl32,)\
    C_MACRO(_ACRTIMP double __cdecl, acos, (double a), (a), acos, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP int __cdecl, __stdio_common_vsprintf, (unsigned __int64 a, char* b, size_t c, const char* d, _locale_t e, va_list f), (a, b, c, d, e, f), __stdio_common_vsprintf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI INT WINAPI, SetScrollInfo, (HWND a, INT b, const SCROLLINFO* c, BOOL d), (a, b, c, d), SetScrollInfo, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(ioctlsocket), (SOCKET a, LONG b, WS(u_long) * c), (a, b, c), ioctlsocket, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI HMENU WINAPI, CreateMenu, (), (), CreateMenu, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ShowWindow, (HWND a, INT b), (a, b), ShowWindow, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreatePath, (GpFillMode a, GpPath** b), (a, b), GdipCreatePath, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, RemoveMenu, (HMENU a, UINT b, UINT c), (a, b, c), RemoveMenu, user32, user32,return)\
    C_MACRO(_ACRTIMP void* __cdecl, _aligned_realloc, (void* a, size_t b, size_t c), (a, b, c), _aligned_realloc, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, CreateWindowExW, (DWORD a, LPCWSTR b, LPCWSTR c, DWORD d, INT e, INT f, INT g, INT h, HWND i, HMENU j, HINSTANCE k, LPVOID l), (a, b, c, d, e, f, g, h, i, j, k, l), CreateWindowExW, user32, user32,return)\
    C_MACRO(WINBASEAPI VOID WINAPI, OutputDebugStringW, (LPCWSTR a), (a), OutputDebugStringW, IumSdk, IumSdk,)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetImageAttributesColorMatrix, (GpImageAttributes* a, ColorAdjustType b, BOOL c, GDIPCONST ColorMatrix* d, GDIPCONST ColorMatrix* e, ColorMatrixFlags f), (a, b, c, d, e, f), GdipSetImageAttributesColorMatrix, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, InsertMenuItemW, (HMENU a, UINT b, BOOL c, const MENUITEMINFOW* d), (a, b, c, d), InsertMenuItemW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipAddPathEllipse, (GpPath* a, REAL b, REAL c, REAL d, REAL e), (a, b, c, d, e), GdipAddPathEllipse, GdiPlus, GdiPlus,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(gethostname), (char * a, int b), (a, b), gethostname, ws2_32, ws2_32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipBitmapLockBits, (GpBitmap* a, GDIPCONST GpRect* b, UINT c, PixelFormat d, BitmapData* e), (a, b, c, d, e), GdipBitmapLockBits, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI LRESULT WINAPI, DispatchMessageW, (const MSG* a), (a), DispatchMessageW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipTranslateWorldTransform, (GpGraphics* a, REAL b, REAL c, GpMatrixOrder d), (a, b, c, d), GdipTranslateWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINSOCK_API_LINKAGE int WINAPI, WSACleanup, (), (), WSACleanup, ws2_32, ws2_32,return)\
    C_MACRO(_ACRTIMP float __cdecl, atan2f, (float a, float b), (a, b), atan2f, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipBitmapUnlockBits, (GpBitmap* a, BitmapData* b), (a, b), GdipBitmapUnlockBits, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, FreeLibrary, (HMODULE a), (a), FreeLibrary, IumSdk, IumSdk,return)\
    C_MACRO(_ACRTIMP void* __cdecl, memmove, (void* a, const void* b, size_t c), (a, b, c), memmove, ucrtbase, ucrtbase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetLinePresetBlend, (GpLineGradient* a, GDIPCONST ARGB* b, GDIPCONST REAL* c, INT d), (a, b, c, d), GdipSetLinePresetBlend, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenDashArray, (GpPen* a, GDIPCONST REAL* b, INT c), (a, b, c), GdipSetPenDashArray, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSaveImageToStream, (GpImage* a, IStream* b, GDIPCONST CLSID* c, GDIPCONST EncoderParameters* d), (a, b, c, d), GdipSaveImageToStream, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, RedrawWindow, (HWND a, const RECT* b, HRGN c, UINT d), (a, b, c, d), RedrawWindow, user32, user32,return)\
    C_MACRO(WINBASEAPI VOID WINAPI, GetSystemTimeAsFileTime, (LPFILETIME a), (a), GetSystemTimeAsFileTime, IumSdk, IumSdk,)\
    C_MACRO(_ACRTIMP int __cdecl, strncmp, (const char* a, const char* b, size_t c), (a, b, c), strncmp, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ClientToScreen, (HWND a, LPPOINT b), (a, b), ClientToScreen, user32, user32,return)\
    C_MACRO(_ACRTIMP double __cdecl, tan, (double a), (a), tan, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP float __cdecl, tanf, (float a), (a), tanf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, WriteFile, (HANDLE a, LPCVOID b, DWORD c, LPDWORD d, LPOVERLAPPED e), (a, b, c, d, e), WriteFile, KernelBase, KernelBase,return)\
    C_MACRO(WINGDIAPI HGDIOBJ WINAPI, GetStockObject, (INT a), (a), GetStockObject, gdi32full, gdi32full,return)\
    C_MACRO(WINBASEAPI HANDLE WINAPI, GetStdHandle, (DWORD a), (a), GetStdHandle, KernelBase, KernelBase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateHICONFromBitmap, (GpBitmap* a, HICON* b), (a, b), GdipCreateHICONFromBitmap, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetWindowRect, (HWND a, LPRECT b), (a, b), GetWindowRect, user32, user32,return)\
    C_MACRO(WINUSERAPI INT WINAPI, MapWindowPoints, (HWND a, HWND b, LPPOINT c, UINT d), (a, b, c, d), MapWindowPoints, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetFileAttributesExW, (LPCWSTR a, GET_FILEEX_INFO_LEVELS b, LPVOID c), (a, b, c), GetFileAttributesExW, KernelBase, KernelBase,return)\
    C_MACRO(Status WINAPI, GdiplusStartup, (ULONG_PTR * a, const struct GdiplusStartupInput * b, struct GdiplusStartupOutput * c), (a, b, c), GdiplusStartup, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ShowScrollBar, (HWND a, INT b, BOOL c), (a, b, c), ShowScrollBar, user32, user32,return)\
    C_MACRO(WINGDIAPI INT WINAPI, ChoosePixelFormat, (HDC a, const PIXELFORMATDESCRIPTOR* b), (a, b), ChoosePixelFormat, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI LONG_PTR WINAPI, SetWindowLongPtrW, (HWND a, INT b, LONG_PTR c), (a, b, c), SetWindowLongPtrW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetWorldTransform, (GpGraphics* a, GpMatrix* b), (a, b), GdipGetWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetScrollInfo, (HWND a, INT b, LPSCROLLINFO c), (a, b, c), GetScrollInfo, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(recv), (SOCKET a, char * b, int c, int d), (a, b, c, d), recv, ws2_32, ws2_32,return)\
    C_MACRO(WINSHELLAPI DWORD_PTR WINAPI, SHGetFileInfoW, (LPCWSTR a, DWORD b, SHFILEINFOW* c, UINT d, UINT e), (a, b, c, d, e), SHGetFileInfoW, windows.storage, windows_storage,return)\
    C_MACRO(WINUSERAPI INT WINAPI, FrameRect, (HDC a, const RECT* b, HBRUSH c), (a, b, c), FrameRect, user32, user32,return)\
    C_MACRO(WINUSERAPI LRESULT WINAPI, CallWindowProcW, (WNDPROC a, HWND b, UINT c, WPARAM d, LPARAM e), (a, b, c, d, e), CallWindowProcW, user32, user32,return)\
    C_MACRO(_ACRTIMP double __cdecl, atan2, (double a, double b), (a, b), atan2, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP errno_t __cdecl, _wcslwr_s, (wchar_t* a, size_t b), (a, b), _wcslwr_s, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, EqualRect, (const RECT* a, const RECT* b), (a, b), EqualRect, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateBitmapFromStreamICM, (IStream* a, GpBitmap** b), (a, b), GdipCreateBitmapFromStreamICM, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI HBITMAP WINAPI, CreateBitmap, (INT a, INT b, UINT c, UINT d, LPCVOID e), (a, b, c, d, e), CreateBitmap, gdi32full, gdi32full,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenBrushFill, (GpPen* a, GpBrush* b), (a, b), GdipSetPenBrushFill, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, FindClose, (HANDLE a), (a), FindClose, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI INT WINAPI, SetScrollPos, (HWND a, INT b, INT c, BOOL d), (a, b, c, d), SetScrollPos, user32, user32,return)\
    C_MACRO(_ACRTIMP errno_t __cdecl, _putenv_s, (const char* a, const char* b), (a, b), _putenv_s, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP float __cdecl, cosf, (float a), (a), cosf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPropertyItemSize, (GpImage* a, PROPID b, UINT* c), (a, b, c), GdipGetPropertyItemSize, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI UINT WINAPI, GetCurrentDirectoryW, (UINT a, LPWSTR b), (a, b), GetCurrentDirectoryW, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, PeekMessageW, (LPMSG a, HWND b, UINT c, UINT d, UINT e), (a, b, c, d, e), PeekMessageW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImagePalette, (GpImage* a, ColorPalette* b, INT c), (a, b, c), GdipGetImagePalette, GdiPlus, GdiPlus,return)\
    C_MACRO(void WINAPI, GdiplusShutdown, (ULONG_PTR a), (a), GdiplusShutdown, GdiPlus, GdiPlus,)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateMatrix2, (REAL a, REAL b, REAL c, REAL d, REAL e, REAL f, GpMatrix** g), (a, b, c, d, e, f, g), GdipCreateMatrix2, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI COLORREF WINAPI, GetSysColor, (INT a), (a), GetSysColor, user32, user32,return)\
    C_MACRO(_ACRTIMP int __cdecl, memcmp, (const void* a, const void* b, size_t c), (a, b, c), memcmp, ucrtbase, ucrtbase,return)\
    C_MACRO(WINUSERAPI HDC WINAPI, GetDC, (HWND a), (a), GetDC, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawImageRectRect, (GpGraphics* a, GpImage* b, REAL c, REAL d, REAL e, REAL f, REAL g, REAL h, REAL i, REAL j, GpUnit k, GDIPCONST GpImageAttributes* l, DrawImageAbort m, VOID* n), (a, b, c, d, e, f, g, h, i, j, k, l, m, n), GdipDrawImageRectRect, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, TerminateThread, (HANDLE a, DWORD b), (a, b), TerminateThread, IumSdk, IumSdk,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, GetFileType, (HANDLE a), (a), GetFileType, KernelBase, KernelBase,return)\
    C_MACRO(HRESULT WINAPI, GetThemeFont, (HTHEME a, HDC b, int c, int d, int e, LOGFONTW* f), (a, b, c, d, e, f), GetThemeFont, uxtheme, uxtheme,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetSmoothingMode, (GpGraphics* a, SmoothingMode b), (a, b), GdipSetSmoothingMode, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP double __cdecl, asin, (double a), (a), asin, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DestroyAcceleratorTable, (HACCEL a), (a), DestroyAcceleratorTable, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(select), (int a, WS(fd_set) * b, WS(fd_set) * c, WS(fd_set) * d, const struct WS(timeval) * e), (a, b, c, d, e), select, ws2_32, ws2_32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, FileTimeToLocalFileTime, (const FILETIME* a, LPFILETIME b), (a, b), FileTimeToLocalFileTime, KernelBase, KernelBase,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, FileTimeToSystemTime, (const FILETIME* a, LPSYSTEMTIME b), (a, b), FileTimeToSystemTime, IumSdk, IumSdk,return)\
    C_MACRO(_ACRTIMP double __cdecl, sqrt, (double a), (a), sqrt, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetMenuItemRect, (HWND a, HMENU b, UINT c, LPRECT d), (a, b, c, d), GetMenuItemRect, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetImagePalette, (GpImage* a, GDIPCONST ColorPalette* b), (a, b), GdipSetImagePalette, GdiPlus, GdiPlus,return)\
    C_MACRO(WINCOMMDLGAPI BOOL WINAPI, GetOpenFileNameW, (LPOPENFILENAMEW ofn), (ofn), GetOpenFileNameW, comdlg32, comdlg32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipMultiplyTextureTransform, (GpTexture* a, GDIPCONST GpMatrix* b, GpMatrixOrder c), (a, b, c), GdipMultiplyTextureTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI void WINAPI, PostQuitMessage, (INT a), (a), PostQuitMessage, user32, user32,)\
    C_MACRO(WINCOMMCTRLAPI HIMAGELIST WINAPI, ImageList_Create, (INT a, INT b, UINT c, INT d, INT e), (a, b, c, d, e), ImageList_Create, comctl32, comctl32,return)\
    C_MACRO(_ACRTIMP float __cdecl, acosf, (float a), (a), acosf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP errno_t __cdecl, wcscpy_s, (wchar_t* a, size_t b, const wchar_t* c), (a, b, c), wcscpy_s, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, TranslateMessage, (const MSG* a), (a), TranslateMessage, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, RemoveDirectoryW, (LPCWSTR a), (a), RemoveDirectoryW, KernelBase, KernelBase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPenWidth, (GpPen* a, REAL* b), (a, b), GdipGetPenWidth, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, TrackPopupMenu, (HMENU a, UINT b, INT c, INT d, INT e, HWND f, const RECT* g), (a, b, c, d, e, f, g), TrackPopupMenu, user32, user32,return)\
    C_MACRO(WINCOMMCTRLAPI BOOL WINAPI, InitCommonControlsEx, (const INITCOMMONCONTROLSEX* a), (a), InitCommonControlsEx, comctl32, comctl32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateFontFamilyFromName, (GDIPCONST WCHAR* a, GpFontCollection* b, GpFontFamily** c), (a, b, c), GdipCreateFontFamilyFromName, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetExitCodeThread, (HANDLE a, LPDWORD b), (a, b), GetExitCodeThread, IumSdk, IumSdk,return)\
    C_MACRO(WINCOMMCTRLAPI BOOL WINAPI, ImageList_Replace, (HIMAGELIST a, INT b, HBITMAP c, HBITMAP d), (a, b, c, d), ImageList_Replace, comctl32, comctl32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, MoveFileW, (LPCWSTR a, LPCWSTR b), (a, b), MoveFileW, kernel32, kernel32,return)\
    C_MACRO(_ACRTIMP void* __cdecl, memcpy, (void* a, const void* b, size_t c), (a, b, c), memcpy, ucrtbase, ucrtbase,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, SetFilePointer, (HANDLE a, LONG b, LPLONG c, DWORD d), (a, b, c, d), SetFilePointer, KernelBase, KernelBase,return)\
    C_MACRO(_ACRTIMP size_t __cdecl, strftime, (char* a, size_t b, const char* c, const struct tm* d), (a, b, c, d), strftime, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(getpeername), (SOCKET a, struct WS(sockaddr) * b, int * c), (a, b, c), getpeername, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, AdjustWindowRectEx, (LPRECT a, DWORD b, BOOL c, DWORD d), (a, b, c, d), AdjustWindowRectEx, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipScaleLineTransform, (GpLineGradient* a, REAL b, REAL c, GpMatrixOrder d), (a, b, c, d), GdipScaleLineTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(void WINGDIPAPI, GdipFree, (void* a), (a), GdipFree, GdiPlus, GdiPlus,)\
    C_MACRO(WINUSERAPI ULONG_PTR WINAPI, GetClassLongPtrW, (HWND a, INT b), (a, b), GetClassLongPtrW, user32, user32,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, GetTextMetricsW, (HDC a, LPTEXTMETRICW b), (a, b), GetTextMetricsW, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, SetParent, (HWND a, HWND b), (a, b), SetParent, user32, user32,return)\
    C_MACRO(WINUSERAPI LONG WINAPI, GetWindowLongW, (HWND a, INT b), (a, b), GetWindowLongW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipImageGetFrameCount, (GpImage* a, GDIPCONST GUID* b, UINT* c), (a, b, c), GdipImageGetFrameCount, GdiPlus, GdiPlus,return)\
    DELAY(C_MACRO, int WINAPI, WS(getnameinfo), (const SOCKADDR* a, WS(socklen_t) b, PCHAR c, DWORD d, PCHAR e, DWORD f, INT g), (a, b, c, d, e, f, g), getnameinfo, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SetMenuItemInfoW, (HMENU a, UINT b, BOOL c, const MENUITEMINFOW* d), (a, b, c, d), SetMenuItemInfoW, user32, user32,return)\
    C_MACRO(WINUSERAPI INT WINAPI, ReleaseDC, (HWND a, HDC b), (a, b), ReleaseDC, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenDashStyle, (GpPen* a, GpDashStyle b), (a, b), GdipSetPenDashStyle, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI INT WINAPI, DrawTextW, (HDC a, LPCWSTR b, INT c, LPRECT d, UINT e), (a, b, c, d, e), DrawTextW, user32, user32,return)\
    C_MACRO(WINUSERAPI INT WINAPI, GetClassNameW, (HWND a, LPWSTR b, INT c), (a, b, c), GetClassNameW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetStringFormatLineAlign, (GpStringFormat* a, StringAlignment b), (a, b), GdipSetStringFormatLineAlign, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetStringFormatAlign, (GpStringFormat* a, StringAlignment b), (a, b), GdipSetStringFormatAlign, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI INT WINAPI, ExcludeClipRect, (HDC a, INT b, INT c, INT d, INT e), (a, b, c, d, e), ExcludeClipRect, gdi32full, gdi32full,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetImagePaletteSize, (GpImage* a, INT* b), (a, b), GdipGetImagePaletteSize, GdiPlus, GdiPlus,return)\
    C_MACRO(INTERNETAPI HINTERNET WINAPI, InternetOpenW, (LPCWSTR a, DWORD b, LPCWSTR c, LPCWSTR d, DWORD e), (a, b, c, d, e), InternetOpenW, wininet, wininet,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenWidth, (GpPen* a, REAL b), (a, b), GdipSetPenWidth, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawArc, (GpGraphics* a, GpPen* b, REAL c, REAL d, REAL e, REAL f, REAL g, REAL h), (a, b, c, d, e, f, g, h), GdipDrawArc, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HICON WINAPI, LoadIconW, (HINSTANCE a, LPCWSTR b), (a, b), LoadIconW, user32, user32,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, SetFocus, (HWND a), (a), SetFocus, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetVersionExW, (OSVERSIONINFOW* a), (a), GetVersionExW, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetCursorPos, (LPPOINT a), (a), GetCursorPos, user32, user32,return)\
    C_MACRO(_ACRTIMP void* __cdecl, memset, (void* a, int b, size_t c), (a, b, c), memset, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DrawFocusRect, (HDC a, const RECT* b), (a, b), DrawFocusRect, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SetWindowPos, (HWND a, HWND b, INT c, INT d, INT e, INT f, UINT g), (a, b, c, d, e, f, g), SetWindowPos, user32, user32,return)\
    C_MACRO(_ACRTIMP int __cdecl, isxdigit, (int a), (a), isxdigit, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, InflateRect, (LPRECT a, INT b, INT c), (a, b, c), InflateRect, user32, user32,return)\
    C_MACRO(WINSOCK_API_LINKAGE SOCKET WINAPI, WSASocketW, (int a, int b, int c, LPWSAPROTOCOL_INFOW d, GROUP e, DWORD f), (a, b, c, d, e, f), WSASocketW, ws2_32, ws2_32,return)\
    C_MACRO(BOOLAPI, HttpSendRequestW, (HINTERNET a, LPCWSTR b, DWORD c, LPVOID d, DWORD e), (a, b, c, d, e), HttpSendRequestW, wininet, wininet,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, SystemTimeToFileTime, (const SYSTEMTIME* a, LPFILETIME b), (a, b), SystemTimeToFileTime, IumSdk, IumSdk,return)\
    C_MACRO(WINCOMMDLGAPI BOOL WINAPI, ChooseColorW, (LPCHOOSECOLORW lpChCol), (lpChCol), ChooseColorW, comdlg32, comdlg32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetPenLineCap197819, (GpPen* a, GpLineCap b, GpLineCap c, GpDashCap d), (a, b, c, d), GdipSetPenLineCap197819, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HDC WINAPI, BeginPaint, (HWND a, LPPAINTSTRUCT b), (a, b), BeginPaint, user32, user32,return)\
    C_MACRO(WINSHELLAPI LPWSTR* WINAPI, CommandLineToArgvW, (LPCWSTR a, int* b), (a, b), CommandLineToArgvW, shell32, shell32,return)\
    C_MACRO(_ACRTIMP errno_t __cdecl, wcscat_s, (wchar_t* a, size_t b, const wchar_t* c), (a, b, c), wcscat_s, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(shutdown), (SOCKET a, int b), (a, b), shutdown, ws2_32, ws2_32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipScaleWorldTransform, (GpGraphics* a, REAL b, REAL c, GpMatrixOrder d), (a, b, c, d), GdipScaleWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINCOMMCTRLAPI INT WINAPI, ImageList_Add, (HIMAGELIST a, HBITMAP b, HBITMAP c), (a, b, c), ImageList_Add, comctl32, comctl32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, CreateDirectoryW, (LPCWSTR a, LPSECURITY_ATTRIBUTES b), (a, b), CreateDirectoryW, KernelBase, KernelBase,return)\
    C_MACRO(WINBASEAPI VOID WINAPI, Sleep, (DWORD a), (a), Sleep, IumSdk, IumSdk,)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPenDashCount, (GpPen* a, INT* b), (a, b), GdipGetPenDashCount, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP unsigned __int64 __cdecl, _strtoui64, (const char* a, char** b, int c), (a, b, c), _strtoui64, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawLine, (GpGraphics* a, GpPen* b, REAL c, REAL d, REAL e, REAL f), (a, b, c, d, e, f), GdipDrawLine, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI SHORT WINAPI, GetAsyncKeyState, (INT a), (a), GetAsyncKeyState, user32, user32,return)\
    C_MACRO(INTERNETAPI HINTERNET WINAPI, HttpOpenRequestW, (HINTERNET a, LPCWSTR b, LPCWSTR c, LPCWSTR d, LPCWSTR e, LPCWSTR * f, DWORD g, DWORD_PTR h), (a, b, c, d, e, f, g, h), HttpOpenRequestW, wininet, wininet,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ScreenToClient, (HWND a, LPPOINT b), (a, b), ScreenToClient, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DestroyMenu, (HMENU a), (a), DestroyMenu, user32, user32,return)\
    C_MACRO(WINUSERAPI UINT WINAPI, MapVirtualKeyW, (UINT a, UINT b), (a, b), MapVirtualKeyW, user32, user32,return)\
    C_MACRO(BOOLAPI, HttpQueryInfoW, (HINTERNET a, DWORD b, LPVOID c, LPDWORD d, LPDWORD e), (a, b, c, d, e), HttpQueryInfoW, wininet, wininet,return)\
    C_MACRO(WINUSERAPI HBRUSH WINAPI, GetSysColorBrush, (INT a), (a), GetSysColorBrush, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateMatrix, (GpMatrix** a), (a), GdipCreateMatrix, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HCURSOR WINAPI, SetCursor, (HCURSOR a), (a), SetCursor, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(getsockopt), (SOCKET a, int b, int c, char * d, int * e), (a, b, c, d, e), getsockopt, ws2_32, ws2_32,return)\
    C_MACRO(WINCOMMCTRLAPI INT WINAPI, ImageList_GetImageCount, (HIMAGELIST a), (a), ImageList_GetImageCount, comctl32, comctl32,return)\
    C_MACRO(WINUSERAPI HACCEL WINAPI, CreateAcceleratorTableW, (LPACCEL a, INT b), (a, b), CreateAcceleratorTableW, user32, user32,return)\
    C_MACRO(WINUSERAPI UINT_PTR WINAPI, SetTimer, (HWND a, UINT_PTR b, UINT c, TIMERPROC d), (a, b, c, d), SetTimer, user32, user32,return)\
    C_MACRO(_ACRTIMP double __cdecl, cos, (double a), (a), cos, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, DeleteObject, (HGDIOBJ a), (a), DeleteObject, gdi32, gdi32,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetDesktopWindow, (), (), GetDesktopWindow, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateLineBrushFromRect, (GDIPCONST GpRectF* a, ARGB b, ARGB c, LinearGradientMode d, GpWrapMode e, GpLineGradient** f), (a, b, c, d, e, f), GdipCreateLineBrushFromRect, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DrawFrameControl, (HDC a, LPRECT b, UINT c, UINT d), (a, b, c, d), DrawFrameControl, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, InvalidateRect, (HWND a, const RECT* b, BOOL c), (a, b, c), InvalidateRect, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, EndMenu, (), (), EndMenu, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetIconInfo, (HICON a, PICONINFO b), (a, b), GetIconInfo, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, SetCurrentDirectoryW, (LPCWSTR a), (a), SetCurrentDirectoryW, KernelBase, KernelBase,return)\
    C_MACRO(WINBASEAPI LPWSTR WINAPI, GetCommandLineW, (), (), GetCommandLineW, IumSdk, IumSdk,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE struct WS(hostent) * WINAPI, WS(gethostbyname), (const char * a), (a), gethostbyname, ws2_32, ws2_32,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, SetWindowOrgEx, (HDC a, INT b, INT c, LPPOINT d), (a, b, c, d), SetWindowOrgEx, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetClientRect, (HWND a, LPRECT b), (a, b), GetClientRect, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, GetMenuItemInfoW, (HMENU a, UINT b, BOOL c, MENUITEMINFOW* d), (a, b, c, d), GetMenuItemInfoW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetTextRenderingHint, (GpGraphics* a, TextRenderingHint b), (a, b), GdipSetTextRenderingHint, GdiPlus, GdiPlus,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(closesocket), (SOCKET a), (a), closesocket, ws2_32, ws2_32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetWorldTransform, (GpGraphics* a, GpMatrix* b), (a, b), GdipSetWorldTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP int __cdecl, strcmp, (const char* a, const char* b), (a, b), strcmp, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetParent, (HWND a), (a), GetParent, user32, user32,return)\
    C_MACRO(WINSHELLAPI LPITEMIDLIST WINAPI, SHBrowseForFolderW, (LPBROWSEINFOW lpbi), (lpbi), SHBrowseForFolderW, shell32, shell32,return)\
    C_MACRO(WINUSERAPI HCURSOR WINAPI, LoadCursorW, (HINSTANCE a, LPCWSTR b), (a, b), LoadCursorW, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, IsWindowEnabled, (HWND a), (a), IsWindowEnabled, user32, user32,return)\
    C_MACRO(_ACRTIMP float __cdecl, sinf, (float a), (a), sinf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipRotateLineTransform, (GpLineGradient* a, REAL b, GpMatrixOrder c), (a, b, c), GdipRotateLineTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI LONG WINAPI, SetWindowLongW, (HWND a, INT b, LONG c), (a, b, c), SetWindowLongW, user32, user32,return)\
    C_MACRO(WINGDIAPI HGDIOBJ WINAPI, SelectObject, (HDC a, HGDIOBJ b), (a, b), SelectObject, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP float __cdecl, log10f, (float a), (a), log10f, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, ChildWindowFromPointEx, (HWND a, POINT b, UINT c), (a, b, c), ChildWindowFromPointEx, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateBitmapFromScan0, (INT a, INT b, INT c, PixelFormat d, BYTE* e, GpBitmap** f), (a, b, c, d, e, f), GdipCreateBitmapFromScan0, GdiPlus, GdiPlus,return)\
    C_MACRO(GLAPI const GLubyte *GLAPIENTRY, glGetString, (GLenum name), (name), glGetString, opengl32, opengl32,return)\
    C_MACRO(_ACRTIMP float __cdecl, floorf, (float a), (a), floorf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINSHELLAPI BOOL WINAPI, SHGetPathFromIDListW, (LPCITEMIDLIST a, LPWSTR b), (a, b), SHGetPathFromIDListW, windows.storage, windows_storage,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, WindowFromPoint, (POINT a), (a), WindowFromPoint, user32, user32,return)\
    C_MACRO(_ACRTIMP double __cdecl, strtod, (const char* a, char** b), (a, b), strtod, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI UINT WINAPI, GetDoubleClickTime, (), (), GetDoubleClickTime, user32, user32,return)\
    C_MACRO(_ACRTIMP float __cdecl, strtof, (const char* a, char** b), (a, b), strtof, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipTranslateTextureTransform, (GpTexture* a, REAL b, REAL c, GpMatrixOrder d), (a, b, c, d), GdipTranslateTextureTransform, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipAddPathString, (GpPath* a, GDIPCONST WCHAR* b, INT c, GDIPCONST GpFontFamily* d, INT e, REAL f, GDIPCONST RectF* g, GDIPCONST GpStringFormat* h), (a, b, c, d, e, f, g, h), GdipAddPathString, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI INT WINAPI, GetDeviceCaps, (HDC a, INT b), (a, b), GetDeviceCaps, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP float __cdecl, logf, (float a), (a), logf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, EndPaint, (HWND a, const PAINTSTRUCT* b), (a, b), EndPaint, user32, user32,return)\
    C_MACRO(_ACRTIMP int __cdecl, isprint, (int a), (a), isprint, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP float __cdecl, asinf, (float a), (a), asinf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, WaitMessage, (), (), WaitMessage, user32, user32,return)\
    C_MACRO(WINUSERAPI LRESULT WINAPI, SendMessageW, (HWND a, UINT b, WPARAM c, LPARAM d), (a, b, c, d), SendMessageW, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(bind), (SOCKET a, const struct WS(sockaddr) * b, int c), (a, b, c), bind, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, EnableWindow, (HWND a, BOOL b), (a, b), EnableWindow, user32, user32,return)\
    C_MACRO(WINGDIAPI UINT WINAPI, SetTextAlign, (HDC a, UINT b), (a, b), SetTextAlign, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP double __cdecl, fmod, (double a, double b), (a, b), fmod, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINBASEAPI HMODULE WINAPI, GetModuleHandleW, (LPCWSTR a), (a), GetModuleHandleW, IumSdk, IumSdk,return)\
    C_MACRO(WINBASEAPI HANDLE WINAPI, CreateFileW, (LPCWSTR a, DWORD b, DWORD c, LPSECURITY_ATTRIBUTES d, DWORD e, DWORD f, HANDLE g), (a, b, c, d, e, f, g), CreateFileW, KernelBase, KernelBase,return)\
    C_MACRO(_ACRTIMP int __cdecl, __stdio_common_vfprintf, (unsigned __int64 a, FILE* b, const char* c, _locale_t d, va_list e), (a, b, c, d, e), __stdio_common_vfprintf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SystemParametersInfoW, (UINT a, UINT b, LPVOID c, UINT d), (a, b, c, d), SystemParametersInfoW, user32, user32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, ReleaseMutex, (HANDLE a), (a), ReleaseMutex, KernelBase, KernelBase,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SetWindowTextW, (HWND a, LPCWSTR b), (a, b), SetWindowTextW, user32, user32,return)\
    C_MACRO(HRESULT WINAPI, GetThemePartSize, (HTHEME a, HDC b, int c, int d, RECT* e, THEMESIZE f, SIZE* g), (a, b, c, d, e, f, g), GetThemePartSize, uxtheme, uxtheme,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, IsWindowVisible, (HWND a), (a), IsWindowVisible, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, PtInRect, (const RECT* a, POINT b), (a, b), PtInRect, user32, user32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, DestroyWindow, (HWND a), (a), DestroyWindow, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetLineWrapMode, (GpLineGradient* a, GpWrapMode b), (a, b), GdipSetLineWrapMode, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP double __cdecl, sin, (double a), (a), sin, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, GetTextExtentPoint32W, (HDC a, LPCWSTR b, INT c, LPSIZE d), (a, b, c, d), GetTextExtentPoint32W, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP float __cdecl, ceilf, (float a), (a), ceilf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPropertyItem, (GpImage* a, PROPID b, UINT c, PropertyItem* d), (a, b, c, d), GdipGetPropertyItem, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI INT WINAPI, EnumFontFamiliesW, (HDC a, LPCWSTR b, FONTENUMPROCW c, LPARAM d), (a, b, c, d), EnumFontFamiliesW, gdi32full, gdi32full,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, DeleteFileW, (LPCWSTR a), (a), DeleteFileW, KernelBase, KernelBase,return)\
    C_MACRO(_ACRTIMP double __cdecl, pow, (double a, double b), (a, b), pow, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(BOOLAPI, InternetReadFile, (HINTERNET a, LPVOID b, DWORD c, LPDWORD d), (a, b, c, d), InternetReadFile, wininet, wininet,return)\
    C_MACRO(WINGDIAPI COLORREF WINAPI, SetBkColor, (HDC a, COLORREF b), (a, b), SetBkColor, gdi32full, gdi32full,return)\
    C_MACRO(WINSOCK_API_LINKAGE int WINAPI, __WSAFDIsSet, (SOCKET a, WS(fd_set)* b), (a, b), __WSAFDIsSet, ws2_32, ws2_32,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, ReadFile, (HANDLE a, LPVOID b, DWORD c, LPDWORD d, LPOVERLAPPED e), (a, b, c, d, e), ReadFile, KernelBase, KernelBase,return)\
    C_MACRO(WINGDIAPI INT WINAPI, SetBkMode, (HDC a, INT b), (a, b), SetBkMode, gdi32full, gdi32full,return)\
    C_MACRO(WGLAPI HGLRC WINAPI, wglGetCurrentContext, (), (), wglGetCurrentContext, opengl32, opengl32,return)\
    C_MACRO(WINSHLWAPI struct IStream * WINAPI, SHCreateMemStream, (const BYTE* a, UINT b), (a, b), SHCreateMemStream, SHCore, SHCore,return)\
    C_MACRO(_ACRTIMP int __cdecl, wcscmp, (const wchar_t* a, const wchar_t* b), (a, b), wcscmp, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI INT WINAPI, GetSystemMetrics, (INT a), (a), GetSystemMetrics, user32, user32,return)\
    C_MACRO(WGLAPI BOOL WINAPI, wglShareLists, (HGLRC a, HGLRC b), (a, b), wglShareLists, opengl32, opengl32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, ValidateRect, (HWND a, const RECT* b), (a, b), ValidateRect, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipFillPath, (GpGraphics* a, GpBrush* b, GpPath* c), (a, b, c), GdipFillPath, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetFocus, (), (), GetFocus, user32, user32,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, DeleteDC, (HDC a), (a), DeleteDC, gdi32full, gdi32full,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(setsockopt), (SOCKET a, int b, int c, const char * d, int e), (a, b, c, d, e), setsockopt, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, IntersectRect, (LPRECT a, const RECT* b, const RECT* c), (a, b, c), IntersectRect, user32, user32,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetCapture, (), (), GetCapture, user32, user32,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, SetPixelFormat, (HDC a, int b, const PIXELFORMATDESCRIPTOR* c), (a, b, c), SetPixelFormat, gdi32full, gdi32full,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawImageRectI, (GpGraphics* a, GpImage* b, INT c, INT d, INT e, INT f), (a, b, c, d, e, f), GdipDrawImageRectI, GdiPlus, GdiPlus,return)\
    C_MACRO(WGLAPI BOOL WINAPI, wglDeleteContext, (HGLRC a), (a), wglDeleteContext, opengl32, opengl32,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, GetCurrentThreadId, (), (), GetCurrentThreadId, IumSdk, IumSdk,return)\
    C_MACRO(WINGDIAPI HDC WINAPI, CreateCompatibleDC, (HDC a), (a), CreateCompatibleDC, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP size_t __cdecl, strlen, (const char* a), (a), strlen, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetMatrixElements, (GDIPCONST GpMatrix* a, REAL* b), (a, b), GdipGetMatrixElements, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipAddPathLine2, (GpPath* a, GDIPCONST GpPointF* b, INT c), (a, b, c), GdipAddPathLine2, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP float __cdecl, modff, (float a, float* b), (a, b), modff, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(send), (SOCKET a, const char * b, int c, int d), (a, b, c, d), send, ws2_32, ws2_32,return)\
    C_MACRO(WINBASEAPI HANDLE WINAPI, CreateThread, (LPSECURITY_ATTRIBUTES a, SIZE_T b, LPTHREAD_START_ROUTINE c, LPVOID d, DWORD e, LPDWORD f), (a, b, c, d, e, f), CreateThread, IumSdk, IumSdk,return)\
    C_MACRO(WINBASEAPI DWORD WINAPI, WaitForSingleObject, (HANDLE a, DWORD b), (a, b), WaitForSingleObject, IumSdk, IumSdk,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, SetMenu, (HWND a, HMENU b), (a, b), SetMenu, user32, user32,return)\
    C_MACRO(WINCOMMDLGAPI BOOL WINAPI, GetSaveFileNameW, (LPOPENFILENAMEW ofn), (ofn), GetSaveFileNameW, comdlg32, comdlg32,return)\
    C_MACRO(_ACRTIMP int __cdecl, iscntrl, (int a), (a), iscntrl, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, PostMessageW, (HWND a, UINT b, WPARAM c, LPARAM d), (a, b, c, d), PostMessageW, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipSetStringFormatTrimming, (GpStringFormat* a, StringTrimming b), (a, b), GdipSetStringFormatTrimming, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGraphicsClear, (GpGraphics* a, ARGB b), (a, b), GdipGraphicsClear, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, KillTimer, (HWND a, UINT_PTR b), (a, b), KillTimer, user32, user32,return)\
    C_MACRO(_ACRTIMP double __cdecl, floor, (double a), (a), floor, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WGLAPI BOOL WINAPI, wglMakeCurrent, (HDC a, HGLRC b), (a, b), wglMakeCurrent, opengl32, opengl32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateHBITMAPFromBitmap, (GpBitmap* a, HBITMAP* b, ARGB c), (a, b, c), GdipCreateHBITMAPFromBitmap, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipGetPenDashArray, (GpPen* a, REAL* b, INT c), (a, b, c), GdipGetPenDashArray, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawString, (GpGraphics* a, GDIPCONST WCHAR* b, INT c, GDIPCONST GpFont* d, GDIPCONST RectF* e, GDIPCONST GpStringFormat* f, GDIPCONST GpBrush* g), (a, b, c, d, e, f, g), GdipDrawString, GdiPlus, GdiPlus,return)\
    C_MACRO(WINCOMMCTRLAPI BOOL WINAPI, ImageList_Remove, (HIMAGELIST a, INT b), (a, b), ImageList_Remove, comctl32, comctl32,return)\
    C_MACRO(WINUSERAPI ATOM WINAPI, RegisterClassExW, (const WNDCLASSEXW * a), (a), RegisterClassExW, user32, user32,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE SOCKET WINAPI, WS(socket), (int a, int b, int c), (a, b, c), socket, ws2_32, ws2_32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipDrawLines, (GpGraphics* a, GpPen* b, GDIPCONST GpPointF* c, INT d), (a, b, c, d), GdipDrawLines, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP int __cdecl, isgraph, (int a), (a), isgraph, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINGDIAPI BOOL WINAPI, BitBlt, (HDC a, INT b, INT c, INT d, INT e, HDC f, INT g, INT h, DWORD i), (a, b, c, d, e, f, g, h, i), BitBlt, gdi32full, gdi32full,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, CloseHandle, (HANDLE a), (a), CloseHandle, IumSdk, IumSdk,return)\
    C_MACRO(WINGDIAPI HBITMAP WINAPI, CreateCompatibleBitmap, (HDC a, INT b, INT c), (a, b, c), CreateCompatibleBitmap, gdi32full, gdi32full,return)\
    C_MACRO(_ACRTIMP int __cdecl, ispunct, (int a), (a), ispunct, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE int WINAPI, WS(connect), (SOCKET a, const struct WS(sockaddr) * b, int c), (a, b, c), connect, ws2_32, ws2_32,return)\
    C_MACRO(WINUSERAPI INT WINAPI, GetScrollPos, (HWND a, INT b), (a, b), GetScrollPos, user32, user32,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreatePen1, (ARGB a, REAL b, GpUnit c, GpPen** d), (a, b, c, d), GdipCreatePen1, GdiPlus, GdiPlus,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, UnregisterClassW, (LPCWSTR a, HINSTANCE b), (a, b), UnregisterClassW, user32, user32,return)\
    C_MACRO(_ACRTIMP float __cdecl, fmodf, (float a, float b), (a, b), fmodf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateSolidFill, (ARGB a, GpSolidFill** b), (a, b), GdipCreateSolidFill, GdiPlus, GdiPlus,return)\
    C_MACRO(WINBASEAPI BOOL WINAPI, GetExitCodeProcess, (HANDLE a, LPDWORD b), (a, b), GetExitCodeProcess, KernelBase, KernelBase,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateBitmapFromHICON, (HICON a, GpBitmap** b), (a, b), GdipCreateBitmapFromHICON, GdiPlus, GdiPlus,return)\
    C_MACRO(WINGDIAPI INT WINAPI, GetObjectW, (HGDIOBJ a, INT b, LPVOID c), (a, b, c), GetObjectW, gdi32full, gdi32full,return)\
    C_MACRO(WINUSERAPI BOOL WINAPI, UnionRect, (LPRECT a, const RECT* b, const RECT* c), (a, b, c), UnionRect, user32, user32,return)\
    C_MACRO(WINSOCK_API_LINKAGE void WINAPI, WSASetLastError, (int a), (a), WSASetLastError, ws2_32, ws2_32,)\
    C_MACRO(WINBASEAPI FARPROC WINAPI, GetProcAddress, (HMODULE a, LPCSTR b), (a, b), GetProcAddress, IumSdk, IumSdk,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipCreateStringFormat, (INT a, LANGID b, GpStringFormat** c), (a, b, c), GdipCreateStringFormat, GdiPlus, GdiPlus,return)\
    C_MACRO(GpStatus WINGDIPAPI, GdipClosePathFigure, (GpPath* a), (a), GdipClosePathFigure, GdiPlus, GdiPlus,return)\
    C_MACRO(_ACRTIMP int __cdecl, __stdio_common_vsprintf_s, (unsigned __int64 a, char* b, size_t c, const char* d, _locale_t e, va_list f), (a, b, c, d, e, f), __stdio_common_vsprintf_s, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(_ACRTIMP int __cdecl, isalnum, (int a), (a), isalnum, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINSOCK_API_LINKAGE int WINAPI, WSAStartup, (WORD a, LPWSADATA b), (a, b), WSAStartup, ws2_32, ws2_32,return)\
    C_MACRO(_ACRTIMP double __cdecl, modf, (double a, double* b), (a, b), modf, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetActiveWindow, (), (), GetActiveWindow, user32, user32,return)\
    C_MACRO(_ACRTIMP void* __cdecl, _aligned_malloc, (size_t a, size_t b), (a, b), _aligned_malloc, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    C_MACRO(WINUSERAPI HWND WINAPI, GetAncestor, (HWND a, UINT b), (a, b), GetAncestor, user32, user32,return)\
    C_MACRO(_ACRTIMP FILE *__cdecl, __acrt_iob_func, (unsigned index), (index), __acrt_iob_func, ucrtbase_clr0400, ucrtbase_clr0400,return)\
    DELAY(C_MACRO, WINSOCK_API_LINKAGE SOCKET WINAPI, WS(accept), (SOCKET a, struct WS(sockaddr) * b, int * c), (a, b, c), accept, ws2_32, ws2_32,return)\
    FOR_MANUAL_WINDOWS_C_FUNCS_DO(C_MACRO)


#define FOR_WINDOWS_CPP_FUNCS_DO(CPP_MACRO) \


#define FOR_REFERENCED_DLLS_DO(DLL_MACRO) \
    DLL_MACRO(comdlg32) \
    DLL_MACRO(ucrtbase) \
    DLL_MACRO(SHCore) \
    DLL_MACRO(gdi32full) \
    DLL_MACRO(KernelBase) \
    DLL_MACRO(comctl32) \
    DLL_MACRO(wininet) \
    DLL_MACRO(windows_storage) \
    DLL_MACRO(ucrtbase_clr0400) \
    DLL_MACRO(ws2_32) \
    DLL_MACRO(opengl32) \
    DLL_MACRO(GdiPlus) \
    DLL_MACRO(IumSdk) \
    DLL_MACRO(shell32) \
    DLL_MACRO(uxtheme) \
    DLL_MACRO(gdi32) \
    DLL_MACRO(user32) \
    DLL_MACRO(kernel32) \


// Remaining symbols:
// symbol: wsprintfW
// symbol: _fltused
// symbol: __chkstk
// symbol: qsort
// symbol: enum Gdiplus::Status __cdecl Gdiplus::GetImageEncodersSize(unsigned int *, unsigned int *)
// symbol: enum Gdiplus::Status __cdecl Gdiplus::GetImageEncoders(unsigned int, unsigned int, class Gdiplus::ImageCodecInfo *)
// symbol: GdipAlloc
// symbol: atexit

