// Autogenerated by gen_inc.c

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#include XSTR(NAPPGUI_H_DIR/core/hfileh.h)

