// AUTOGENERATED FILE

#include "conf.h"

#define WINE_WINAPI
#define _SCRT_STARTUP_WINMAIN

// Clang defines __SIZEOF_INT128__, and on GNU platforms, this indicates
// that __int128 is present or available. See:
// https://gcc.gnu.org/legacy-ml/gcc-help/2015-08/msg00185.html
// However, /usr/include/x86_64-linux-gnu/c++/12/bits/c++config.h on my
// Linux machine expects other macros to be #defined alongside it. Clang
// just doesn't #define these macros for MSVC targets. NAppGUI #includes
// <bits/c++config.h> indirectly through <typeinfo> in core/arrst.hpp, causing
// a warning. I #undef __SIZEOF_INT128__, since using __int128 doesn't really
// make sense in the current context.
//#undef __SIZEOF_INT128__
// Wine doesn't have GL/glu.h, so I #define GLEW_NO_GLU to indicate this.
#define GLEW_NO_GLU
// #defining _WINSOCKAPI_ prevents a whole bunch of bad refinitions.
// https://stackoverflow.com/a/9168850
#define _WINSOCKAPI_
// NAppGUI requires Unicode to be enabled. In draw2d/win/draw_win.cpp,
// _draw_word_extents passes a WCHAR[256] into GetTextExtentPoint32, which
// only works if it resolves to GetTextExtentPoint32W (the Unicode version
// of the function.) To solve this, I #define UNICODE.
#define UNICODE
// In C++ this answer says that L"string" literals are guarunteed to be
// represented as wchar_t's. https://stackoverflow.com/a/1810488
// NAppGUI assumes these can be considered to be WCHARs, however Winelib
// only typedef's WCHAR to wchar_t if WINE_UNICODE_NATIVE is #defined. See
// Winelib's winnt.h
#define WINE_UNICODE_NATIVE
// I keep getting a DECLSPEC_UUID(x) redefinition warning and I'm convinced
// it doesn't matter. The DECLSPEC_UUID(x) that's defined in winnt.h doesn't
// #define itself if DECLSPEC_UUID(x) is already #defined, so I'm going
// to copy the #define in rpcndr.h
#define DECLSPEC_UUID(x)

// If __declspec(dllimport) is used in a function declaration then the compiler
// requires that the function be defined externally in a DLL. In my case,
// I want to implement standard library functions locally, so I'm going
// to #define _ACRTIMP manually so that it doesn't get #defined to
// __declspec(dllimport) in corecrt.h, and #define WINBASEAPI, WGLAPI,
// INTERNETAPI, WINUSERAPI, WINGDIAPI, WINSHELLAPI, WINSHLWAPI, WINCOMMCTRLAPI, WINCOMMDLGAPI, and WINSOCK_API_LINKAGE so that none of them
// get #defined to DECLSPEC_IMPORT in winbase.h, (DECLSPEC_IMPORT is #defined
// to __declspec(dllimport) in winnt.h) and #define GLAPI so that it doesn't
// get #defined in NAppGUI's in winuser.h
// Edit: __declspec(dllimport) is now having different problems.
#ifdef WINE_WINAPI
#define _ACRTIMP
#define WINBASEAPI
#define WGLAPI
#define INTERNETAPI
#define WINUSERAPI
#define WINGDIAPI
#define WINSHELLAPI
#define WINSHLWAPI
#define WINCOMMCTRLAPI
#define WINCOMMDLGAPI
#define WINSOCK_API_LINKAGE
#define GLAPI
// This one initializes FrameDimensionTime in gdiplusimaging.h and guiddef.h
// It doesn't matter what compilation unit it's #defined in, so long as
// it's only #defined in one.
#ifdef __cplusplus
#define INITGUID

#endif
#endif

// #including <windows.h> with WIN32_LEAN_AND_MEAN #defined  means that
// some Windows headers will not be #included, due to the header guard,
// even if windows.h is #included a second time without WIN32_LEAN_AND_MEAN
// #defined. To solve this, I just #include <windows.h> right here.
#include <windows.h>

// Winelib doesn't make use of extern "C" guards in all of its headers.
// (Unlike Windows? I don't read their headers so I don't know.) As a result,
// when Winelib headers are #included in C++ code, C++ mangles many of its
// symbols. In order to work on /inc/winelib_supplementary/gdip_wrapper.h
// I am linking with Windows libraries using Winelib headers. To solve the
// C++ linkage problem, I just found every Windows/Winelib header that NAppGUI
// #includes, and I #include them in an extern "C" guard right here.

// Actually, some of these headers are part of Clang's libc++ and are smart.
#if defined(__cplusplus)
extern "C" {
////#include <errno.h>
//#include <fcntl.h>
////#include <inttypes.h>
//#include <signal.h>
////#include <stdint.h>
////#include <string.h>
//#include <VersionHelpers.h>
//#include <windows.h>
//#include <WinInet.h>
//#include <winsock2.h>
//#include <uxtheme.h>
}
#endif // __cplusplus

// I have found multiple people doing similar things to me and running into
// the unresolved symbol const type_info::`vftable`. Example:
// https://stackoverflow.com/a/30146974 The generally recommended solution
// is to disable runtime type information (RTTI) using the /GR- flag, or
// in our case, the -fno-rtti flag. Of course, the code uses typeid(), so
// I also create this short snippet to replace typeid().
#ifdef __cplusplus
typedef const char *(*Text_Printer)(void);
const char *print_unknown_type(void) {
    return "[unknown runtime type]";
}
struct DummyTypeidStruct {
    Text_Printer name;
};
DummyTypeidStruct dummy_typeid = {
    .name = print_unknown_type
};
#define typeid(x) dummy_typeid
#endif

// In order to eliminate a dependency on the Windows C++ standard library
// implementation, I have decided to compile libc++ at the same time as
// my code.
#if defined(WINE_WINAPI) && defined(__cplusplus)
#define constinit
#include "libcxx_src/new.cpp"
#include "libcxx_src/new_handler.cpp"
#include "libcxx_src/new_helpers.cpp"
#include "libcxx_src/verbose_abort.cpp"
#undef constinit
#endif

#include "nappgui_src/core/core.cpp"

#include "nappgui_src/core/event.cpp"

// ===== manual directives start =====
// Clang expects a separate declaration for each specialization of a static
// function pointer template before the specialization may be used. Any
// use of such a specialized template before it is declared is considered
// an "implicit instantiation requirement". This requirement is only enforced
// when instantiation of the static function pointer occurs after the implicit
// instantiation requirement and within the same module, since Clang implicitly
// considers it double instantiation.
#if defined(__clang__)
#include <typeinfo>
#include "nappgui_src/geom2d/pol2d.hpp"
#include "nappgui_src/geom2d/obb2d.hpp"
template<>
const V2D< real64_t > *(*Pol2D< real64_t >::points)(const Pol2D< real64_t > *);
template<>
uint32_t (*Pol2D< real64_t >::n)(const Pol2D< real64_t > *);
template<>
const V2D< real64_t > *(*OBB2D< real64_t >::corners)(const OBB2D< real64_t > *);
#endif // __clang__
// ===== manual directives end =====


#include "nappgui_src/draw2d/drawg.cpp"

#include "nappgui_src/geom2d/box2d.cpp"


#define i_from_points i_from_points_cir2d
#define i_area i_area_cir2d
#define i_is_null i_is_null_cir2d
#include "nappgui_src/geom2d/cir2d.cpp"
#undef i_from_points
#undef i_area
#undef i_is_null

#include "nappgui_src/geom2d/col2d.cpp"

#define i_create i_create_obb2d
#define i_from_points i_from_points_obb2d
#define i_copy i_copy_obb2d
#define i_destroy i_destroy_obb2d
#define i_center i_center_obb2d
#define i_area i_area_obb2d
// ===== manual directives start =====
// Windows's (and Winelib's) windef.h file #defines max and min macros,
// which causes problems.
#ifdef min
#undef min
#endif
#ifdef max
#undef max
#endif
// ===== manual directives end =====
#include "nappgui_src/geom2d/obb2d.cpp"
#undef i_create
#undef i_from_points
#undef i_copy
#undef i_destroy
#undef i_center
#undef i_area

#define i_create i_create_pol2d
#define i_copy i_copy_pol2d
#define i_destroy i_destroy_pol2d
#define i_transform i_transform_pol2d
#define i_area i_area_pol2d
#define i_box i_box_pol2d
#define i_sat_poly i_sat_poly_pol2d
#include "nappgui_src/geom2d/pol2d.cpp"
#undef i_create
#undef i_copy
#undef i_destroy
#undef i_transform
#undef i_area
#undef i_box
#undef i_sat_poly

#include "nappgui_src/geom2d/polabel.cpp"

#include "nappgui_src/geom2d/polpart.cpp"

#define i_center i_center_r2d
#include "nappgui_src/geom2d/r2d.cpp"
#undef i_center

#include "nappgui_src/geom2d/s2d.cpp"

#include "nappgui_src/geom2d/seg2d.cpp"

#define i_move i_move_t2d
#include "nappgui_src/geom2d/t2d.cpp"
#undef i_move

#define i_transform i_transform_tri2d
#define i_area i_area_tri2d
#define i_ccw i_ccw_tri2d
#define i_centroid i_centroid_tri2d
#include "nappgui_src/geom2d/tri2d.cpp"
#undef i_transform
#undef i_area
#undef i_ccw
#undef i_centroid

#define i_add i_add_v2d
#define i_length i_length_v2d
#define i_sqlength i_sqlength_v2d
#define i_dist i_dist_v2d
#define i_sqdist i_sqdist_v2d
#define i_angle i_angle_v2d
#define i_rotate i_rotate_v2d
#include "nappgui_src/geom2d/v2d.cpp"
#undef i_add
#undef i_length
#undef i_sqlength
#undef i_dist
#undef i_sqdist
#undef i_angle
#undef i_rotate

#include "nappgui_src/sewer/bmath.cpp"


#include "nappgui_src/draw2d/win/dctx_win.cpp"


#define i_color i_color_draw_win
#include "nappgui_src/draw2d/win/draw_win.cpp"
#undef i_color


#include "nappgui_src/draw2d/win/osfont.cpp"

#include "nappgui_src/draw2d/win/osimage.cpp"

#include "nappgui_src/osgui/win/oscontrol.cpp"

#include "nappgui_src/osgui/win/osdrawctrl.cpp"

#define i_GDIPLUSTOKEN i_GDIPLUSTOKEN_osgui_win
#include "nappgui_src/osgui/win/osgui_win.cpp"
#undef i_GDIPLUSTOKEN

#include "nappgui_src/osgui/win/osimg.cpp"

#include "nappgui_src/osgui/win/osview.cpp"

#define i_WndProc i_WndProc_osweb
#include "nappgui_src/osgui/win/osweb.cpp"
#undef i_WndProc

#include "resolve_windows_symbols.cpp"

