// AUTOGENERATED FILE

#include "conf.h"

#define WINE_WINAPI
#define _SCRT_STARTUP_WINMAIN

// Clang defines __SIZEOF_INT128__, and on GNU platforms, this indicates
// that __int128 is present or available. See:
// https://gcc.gnu.org/legacy-ml/gcc-help/2015-08/msg00185.html
// However, /usr/include/x86_64-linux-gnu/c++/12/bits/c++config.h on my
// Linux machine expects other macros to be #defined alongside it. Clang
// just doesn't #define these macros for MSVC targets. NAppGUI #includes
// <bits/c++config.h> indirectly through <typeinfo> in core/arrst.hpp, causing
// a warning. I #undef __SIZEOF_INT128__, since using __int128 doesn't really
// make sense in the current context.
//#undef __SIZEOF_INT128__
// Wine doesn't have GL/glu.h, so I #define GLEW_NO_GLU to indicate this.
#define GLEW_NO_GLU
// #defining _WINSOCKAPI_ prevents a whole bunch of bad refinitions.
// https://stackoverflow.com/a/9168850
#define _WINSOCKAPI_
// NAppGUI requires Unicode to be enabled. In draw2d/win/draw_win.cpp,
// _draw_word_extents passes a WCHAR[256] into GetTextExtentPoint32, which
// only works if it resolves to GetTextExtentPoint32W (the Unicode version
// of the function.) To solve this, I #define UNICODE.
#define UNICODE
// In C++ this answer says that L"string" literals are guarunteed to be
// represented as wchar_t's. https://stackoverflow.com/a/1810488
// NAppGUI assumes these can be considered to be WCHARs, however Winelib
// only typedef's WCHAR to wchar_t if WINE_UNICODE_NATIVE is #defined. See
// Winelib's winnt.h
#define WINE_UNICODE_NATIVE
// I keep getting a DECLSPEC_UUID(x) redefinition warning and I'm convinced
// it doesn't matter. The DECLSPEC_UUID(x) that's defined in winnt.h doesn't
// #define itself if DECLSPEC_UUID(x) is already #defined, so I'm going
// to copy the #define in rpcndr.h
#define DECLSPEC_UUID(x)

// If __declspec(dllimport) is used in a function declaration then the compiler
// requires that the function be defined externally in a DLL. In my case,
// I want to implement standard library functions locally, so I'm going
// to #define _ACRTIMP manually so that it doesn't get #defined to
// __declspec(dllimport) in corecrt.h, and #define WINBASEAPI, WGLAPI,
// INTERNETAPI, WINUSERAPI, WINGDIAPI, WINSHELLAPI, WINSHLWAPI, WINCOMMCTRLAPI, WINCOMMDLGAPI, and WINSOCK_API_LINKAGE so that none of them
// get #defined to DECLSPEC_IMPORT in winbase.h, (DECLSPEC_IMPORT is #defined
// to __declspec(dllimport) in winnt.h) and #define GLAPI so that it doesn't
// get #defined in NAppGUI's in winuser.h
// Edit: __declspec(dllimport) is now having different problems.
#ifdef WINE_WINAPI
#define _ACRTIMP
#define WINBASEAPI
#define WGLAPI
#define INTERNETAPI
#define WINUSERAPI
#define WINGDIAPI
#define WINSHELLAPI
#define WINSHLWAPI
#define WINCOMMCTRLAPI
#define WINCOMMDLGAPI
#define WINSOCK_API_LINKAGE
#define GLAPI
// This one initializes FrameDimensionTime in gdiplusimaging.h and guiddef.h
// It doesn't matter what compilation unit it's #defined in, so long as
// it's only #defined in one.
#ifdef __cplusplus
#define INITGUID

#endif
#endif

// #including <windows.h> with WIN32_LEAN_AND_MEAN #defined  means that
// some Windows headers will not be #included, due to the header guard,
// even if windows.h is #included a second time without WIN32_LEAN_AND_MEAN
// #defined. To solve this, I just #include <windows.h> right here.
#include <windows.h>

// Winelib doesn't make use of extern "C" guards in all of its headers.
// (Unlike Windows? I don't read their headers so I don't know.) As a result,
// when Winelib headers are #included in C++ code, C++ mangles many of its
// symbols. In order to work on /inc/winelib_supplementary/gdip_wrapper.h
// I am linking with Windows libraries using Winelib headers. To solve the
// C++ linkage problem, I just found every Windows/Winelib header that NAppGUI
// #includes, and I #include them in an extern "C" guard right here.

// Actually, some of these headers are part of Clang's libc++ and are smart.
#if defined(__cplusplus)
extern "C" {
////#include <errno.h>
//#include <fcntl.h>
////#include <inttypes.h>
//#include <signal.h>
////#include <stdint.h>
////#include <string.h>
//#include <VersionHelpers.h>
//#include <windows.h>
//#include <WinInet.h>
//#include <winsock2.h>
//#include <uxtheme.h>
}
#endif // __cplusplus

// I have found multiple people doing similar things to me and running into
// the unresolved symbol const type_info::`vftable`. Example:
// https://stackoverflow.com/a/30146974 The generally recommended solution
// is to disable runtime type information (RTTI) using the /GR- flag, or
// in our case, the -fno-rtti flag. Of course, the code uses typeid(), so
// I also create this short snippet to replace typeid().
#ifdef __cplusplus
typedef const char *(*Text_Printer)(void);
const char *print_unknown_type(void) {
    return "[unknown runtime type]";
}
struct DummyTypeidStruct {
    Text_Printer name;
};
DummyTypeidStruct dummy_typeid = {
    .name = print_unknown_type
};
#define typeid(x) dummy_typeid
#endif

// In order to eliminate a dependency on the Windows C++ standard library
// implementation, I have decided to compile libc++ at the same time as
// my code.
#if defined(WINE_WINAPI) && defined(__cplusplus)
#define constinit
#include <new.cpp>
#include <new_handler.cpp>
#include <new_helpers.cpp>
#include <verbose_abort.cpp>
#undef constinit
#endif

#include "nappgui_src/core/array.c"

#include "nappgui_src/core/bhash.c"

#include "nappgui_src/core/buffer.c"
// ===== manual directives start =====
#undef i_SIZE
#undef i_DATA
// ===== manual directives end =====

#include "nappgui_src/core/clock.c"

#include "nappgui_src/core/date.c"

// ===== manual directives start =====
// EnumProps is a Windows symbol appropriated by dbind.c, which doesn't
// expect to be working in the same namespace as Windows headers. I #undef
// EnumProps to avoid this.
#if defined(EnumProps) && EnumProps == EnumPropsW
#define REDEFINE_ENUM_PROPS_W
#undef EnumProps
#elif defined(EnumProps) && EnumProps == EnumPropsA
#define REDEFINE_ENUM_PROPS_A
#undef EnumProps
#endif
// ===== manual directives end =====
#include "nappgui_src/core/dbind.c"
// ===== manual directives start =====
#ifdef REDEFINE_ENUM_PROPS_W
#undef REDEFINE_ENUM_PROPS_W
#define EnumProps EnumPropsW
#endif
#ifdef REDEFINE_ENUM_PROPS_A
#undef REDEFINE_ENUM_PROPS_A
#define EnumProps EnumPropsW
#endif
// ===== manual directives end =====

#define i_next_pow2 i_next_pow2_heap
#include "nappgui_src/core/heap.c"
#undef i_next_pow2

#include "nappgui_src/core/hfile.c"

#include "nappgui_src/core/keybuf.c"

// ===== manual directives start =====
// gui_state_t is also declared in the header file draw2d/guictx.hxx
#ifndef gui_state_t
#define gui_state_t gui_state_t_lex
#endif
// ===== manual directives end =====
#include "nappgui_src/core/lex.c"
// ===== manual directives start =====
#undef gui_state_t
// ===== manual directives end =====

// ===== manual directives start =====
// symbol_t isn't re-used and can cause problems similar to PElem (see gui/listbox.c) if it's #defined to symbol_t_nfa.
#ifdef symbol_t
#undef symbol_t
#define symbol_t symbol_t
#endif
// ===== manual directives end =====
#include "nappgui_src/core/nfa.c"

#include "nappgui_src/core/obj.c"

#include "nappgui_src/core/rbtree.c"

#include "nappgui_src/core/regex.c"

#define i_type_t i_type_t_respack
#include "nappgui_src/core/respack.c"
#undef i_type_t

#define i_type_t i_type_t_stream
#define i_next_pow2 i_next_pow2_stream
#include "nappgui_src/core/stream.c"
#undef i_type_t
#undef i_next_pow2

#include "nappgui_src/core/strings.c"
// ===== manual directives start =====
#undef i_SIZE
#undef i_DATA
// ===== manual directives end =====

#define _state_t _state_t_tfilter
#define stSTART stSTART_tfilter
#define stZERO stZERO_tfilter
#define stREAL stREAL_tfilter
#define gui_state_t gui_state_t_tfilter
// ===== manual directives start =====
// gui_state_t is also declared in the header file draw2d/guictx.hxx
#ifndef gui_state_t
#define gui_state_t gui_state_t_tfilter
#endif
// ===== manual directives end =====
#include "nappgui_src/core/tfilter.c"
#undef _state_t
#undef stSTART
#undef stZERO
#undef stREAL
#undef gui_state_t
// ===== manual directives start =====
#undef gui_state_t
// ===== manual directives end =====

#include "nappgui_src/draw2d/color.c"
// ===== manual directives start =====
// color.c #defines a lot of simple macros. Similar macros are #defined
// in osgui/gtk/ospanel.c Here we #undef these macros to silence annoying
// redefinition warnings.
#undef i_red
#undef i_green
#undef i_blue
#undef i_alpha
// ===== manual directives end =====

#include "nappgui_src/draw2d/dctx.c"

#include "nappgui_src/draw2d/draw2d.c"

#include "nappgui_src/draw2d/font.c"

#include "nappgui_src/draw2d/guictx.c"

#include "nappgui_src/draw2d/image.c"

#include "nappgui_src/draw2d/imgutil.c"
// ===== manual directives start =====
// On line 1189, imgutil.c #defines an i_color macro. Functions with the
// name i_color are used in a lot of other draw2d and osgui source files.
// It's best to #undef the i_color macro now to avoid conflicting usages.
#undef i_color
// ===== manual directives end =====

#include "nappgui_src/draw2d/palette.c"

#include "nappgui_src/draw2d/pixbuf.c"
// ===== manual directives start =====
#undef i_DATA
// ===== manual directives end =====

#include "nappgui_src/encode/base64.c"

#define i_NUM_USERS i_NUM_USERS_encode
#include "nappgui_src/encode/encode.c"
#undef i_NUM_USERS

#define i_write_container i_write_container_json
#define i_write_binary i_write_binary_json
#include "nappgui_src/encode/json.c"
#undef i_write_container
#undef i_write_binary

#include "nappgui_src/encode/url.c"

#define i_create i_create_button
#include "nappgui_src/gui/button.c"
#undef i_create

#include "nappgui_src/gui/combo.c"

#include "nappgui_src/gui/component.c"

#include "nappgui_src/gui/comwin.c"

#include "nappgui_src/gui/drawctrl.c"

#define i_OnFilter i_OnFilter_edit
#define i_OnChange i_OnChange_edit
#define i_OnFocus i_OnFocus_edit
#define i_create i_create_edit
#include "nappgui_src/gui/edit.c"
#undef i_OnFilter
#undef i_OnChange
#undef i_OnFocus
#undef i_create

#define i_create i_create_editimp
#include "nappgui_src/gui/editimp.c"
#undef i_create

#define i_set_bool i_set_bool_gbind
#define i_set_real i_set_real_gbind
#define i_set_enum i_set_enum_gbind
#include "nappgui_src/gui/gbind.c"
#undef i_set_bool
#undef i_set_real
#undef i_set_enum

#include "nappgui_src/gui/globals.c"

#define i_NUM_USERS i_NUM_USERS_gui
#include "nappgui_src/gui/gui.c"
#undef i_NUM_USERS

#include "nappgui_src/gui/guicontrol.c"

#define i_destroy_data i_destroy_data_imageview
#define i_OnExit i_OnExit_imageview
#include "nappgui_src/gui/imageview.c"
#undef i_destroy_data
#undef i_OnExit

#define i_create i_create_items
#include "nappgui_src/gui/items.c"
#undef i_create

#define i_create i_create_label
#define i_OnClick i_OnClick_label
#include "nappgui_src/gui/label.c"
#undef i_create
#undef i_OnClick

#define i_EPSILON i_EPSILON_layout
#include "nappgui_src/gui/layout.c"
#undef i_EPSILON

#define _pelem_t _pelem_t_listbox
#define i_remove_elem i_remove_elem_listbox
#define i_destroy_data i_destroy_data_listbox
#define i_OnDraw i_OnDraw_listbox
#define i_OnEnter i_OnEnter_listbox
#define i_OnExit i_OnExit_listbox
#define i_OnFocus i_OnFocus_listbox
#define i_set_empty i_set_empty_listbox
// ===== manual directives start =====
// There is an annoying quirk in how preprocessor directives work. In the
// code, there are macros for arrst_destroy() and PElem. The following line
// of code in gui/listbox.c line 118
//     arrst_destroy(&(*data)->elems, i_remove_elem, PElem);
// expands arrst_destroy first, substituting PElem to produce
// arrst_PElem_destroy before PElem can be rewritten into PElem_listbox
// and produce arrst_PElem_listbox_destroy, which is what we wanted. That
// means that we need an additional preprocessor macro to convert
// arrst_PElem_destroy into arrst_PElem_listbox_destroy after the fact.
#define PElem PElem_listbox
#define ArrStPElem ArrStPElem_listbox
#define arrst_PElem_destroy arrst_PElem_listbox_destroy
#define arrst_PElem_create arrst_PElem_listbox_create
#define arrst_PElem_size arrst_PElem_listbox_size
#define arrst_PElem_all arrst_PElem_listbox_all
#define arrst_PElem_get arrst_PElem_listbox_get
#define arrst_PElem_insert0 arrst_PElem_listbox_insert0
#define arrst_PElem_delete arrst_PElem_listbox_delete
#define arrst_PElem_clear arrst_PElem_listbox_clear
// ===== manual directives end =====
#include "nappgui_src/gui/listbox.c"
#undef _pelem_t
#undef i_remove_elem
#undef i_destroy_data
#undef i_OnDraw
#undef i_OnEnter
#undef i_OnExit
#undef i_OnFocus
#undef i_set_empty
// ===== manual directives start =====
#undef PElem
#undef ArrStPElem
#undef arrst_PElem_destroy
#undef arrst_PElem_create
#undef arrst_PElem_size
#undef arrst_PElem_all
#undef arrst_PElem_get
#undef arrst_PElem_insert0
#undef arrst_PElem_delete
#undef arrst_PElem_clear
// ===== manual directives end =====

#define i_destroy i_destroy_menu
#include "nappgui_src/gui/menu.c"
#undef i_destroy

#define i_create i_create_menuitem
#define i_update_text i_update_text_menuitem
#include "nappgui_src/gui/menuitem.c"
#undef i_create
#undef i_update_text

#define i_create i_create_panel
#include "nappgui_src/gui/panel.c"
#undef i_create

#define i_OnSelect i_OnSelect_popup
#include "nappgui_src/gui/popup.c"
#undef i_OnSelect

#define i_create i_create_progress
#include "nappgui_src/gui/progress.c"
#undef i_create

#include "nappgui_src/gui/res_gui.c"

#include "nappgui_src/gui/scrollview.c"

#define i_create i_create_slider
#include "nappgui_src/gui/slider.c"
#undef i_create

#define i_create i_create_splitview
#include "nappgui_src/gui/splitview.c"
#undef i_create

#define _ctype_t _ctype_t_tableview
#define ctype_t ctype_t_tableview
#define i_BOTTOM_PADDING i_BOTTOM_PADDING_tableview
#define i_create_data i_create_data_tableview
#define i_destroy_data i_destroy_data_tableview
#define i_OnDraw i_OnDraw_tableview
#define i_document_size i_document_size_tableview
#define i_OnSize i_OnSize_tableview
#define i_OnMove i_OnMove_tableview
#define i_OnDrag i_OnDrag_tableview
#define i_OnExit i_OnExit_tableview
#define i_OnFocus i_OnFocus_tableview
#define i_select i_select_tableview
#define i_OnDown i_OnDown_tableview
#define i_OnUp i_OnUp_tableview
#define i_update_sel_top i_update_sel_top_tableview
#define i_update_sel_bottom i_update_sel_bottom_tableview
#define i_OnKeyDown i_OnKeyDown_tableview
#define i_OnKeyUp i_OnKeyUp_tableview
#include "nappgui_src/gui/tableview.c"
#undef _ctype_t
#undef ctype_t
#undef i_BOTTOM_PADDING
#undef i_create_data
#undef i_destroy_data
#undef i_OnDraw
#undef i_document_size
#undef i_OnSize
#undef i_OnMove
#undef i_OnDrag
#undef i_OnExit
#undef i_OnFocus
#undef i_select
#undef i_OnDown
#undef i_OnUp
#undef i_update_sel_top
#undef i_update_sel_bottom
#undef i_OnKeyDown
#undef i_OnKeyUp

#define i_OnFilter i_OnFilter_textview
#define i_OnFocus i_OnFocus_textview
#include "nappgui_src/gui/textview.c"
#undef i_OnFilter
#undef i_OnFocus

#define i_OnClick i_OnClick_updown
#include "nappgui_src/gui/updown.c"
#undef i_OnClick

#define i_OnDraw i_OnDraw_view
#define i_OnOverlay i_OnOverlay_view
#define i_OnEnter i_OnEnter_view
#define i_OnExit i_OnExit_view
#define i_OnDown i_OnDown_view
#define i_OnUp i_OnUp_view
#define i_OnClick i_OnClick_view
#define i_OnDrag i_OnDrag_view
#define i_OnKeyDown i_OnKeyDown_view
#define i_OnKeyUp i_OnKeyUp_view
#define i_OnFocus i_OnFocus_view
#define i_OnAcceptFocus i_OnAcceptFocus_view
#define i_OnScroll i_OnScroll_view
#define i_create i_create_view
#include "nappgui_src/gui/view.c"
#undef i_OnDraw
#undef i_OnOverlay
#undef i_OnEnter
#undef i_OnExit
#undef i_OnDown
#undef i_OnUp
#undef i_OnClick
#undef i_OnDrag
#undef i_OnKeyDown
#undef i_OnKeyUp
#undef i_OnFocus
#undef i_OnAcceptFocus
#undef i_OnScroll
#undef i_create

#define i_OnFocus i_OnFocus_webview
#include "nappgui_src/gui/webview.c"
#undef i_OnFocus

#define i_destroy i_destroy_window
#include "nappgui_src/gui/window.c"
#undef i_destroy

#define i_create i_create_httpreq
#include "nappgui_src/inet/httpreq.c"
#undef i_create

#define i_NUM_USERS i_NUM_USERS_inet
#include "nappgui_src/inet/inet.c"
#undef i_NUM_USERS

// ===== manual directives start =====
// ogl3d/glew.c #includes ogl3d/glxew.h
// ogl3d/glxew.h #includes X11/Xlib.h
// X11/Xlib.h #includes X11/X.h
// and X11/X.h dumps a bunch of typedefs into the global namespace, squatting 
// such identifiers as Mask, Atom, Time, Window, Font, Cursor, and KeyCode.
// Dang it X11! We actually need some of those!
#define Font Font_X11
#define Cursor Cursor_X11
#define Window Window_X11
// ===== manual directives end =====
#include "nappgui_src/ogl3d/glew.c"
// ===== manual directives start =====
// The NAppGUI authors are lazy and didn't bother to re-enable warn.hxx
// at the end of ogl3d/glew.c. This only matters for unity builds though,
// so it's kind of unreasonable to expect that from them anyway.
#include "nappgui_src/sewer/warn.hxx"

#undef Font
#undef Cursor
#undef Window
// ===== manual directives end =====

#define i_NUM_USERS i_NUM_USERS_ogl3d
#include "nappgui_src/ogl3d/ogl3d.c"
#undef i_NUM_USERS

#define _icon_t _icon_t_osapp
#define icon_t icon_t_osapp
#include "nappgui_src/osapp/osapp.c"
#undef _icon_t
#undef icon_t

#include "nappgui_src/osbs/bsocket.c"

#include "nappgui_src/osbs/log.c"

#define i_NUM_USERS i_NUM_USERS_osbs
#include "nappgui_src/osbs/osbs.c"
#undef i_NUM_USERS

#include "nappgui_src/osgui/osbutton.c"

#include "nappgui_src/osgui/oscombo.c"

#include "nappgui_src/osgui/oscontrol.c"

#include "nappgui_src/osgui/osedit.c"

#define i_NUM_USERS i_NUM_USERS_osgui
#define i_DEFAULT_FONT i_DEFAULT_FONT_osgui
#include "nappgui_src/osgui/osgui.c"
#undef i_NUM_USERS
#undef i_DEFAULT_FONT

#include "nappgui_src/osgui/osguictx.c"

#include "nappgui_src/osgui/oslabel.c"

#include "nappgui_src/osgui/ospanel.c"

#include "nappgui_src/osgui/ospopup.c"

#include "nappgui_src/osgui/osprogress.c"

#include "nappgui_src/osgui/osscrolls.c"

#include "nappgui_src/osgui/osslider.c"

#include "nappgui_src/osgui/ossplit.c"

#include "nappgui_src/osgui/ostabstop.c"

#include "nappgui_src/osgui/ostext.c"

#include "nappgui_src/osgui/osupdown.c"

#include "nappgui_src/osgui/osview.c"

#include "nappgui_src/osgui/osweb.c"

#include "nappgui_src/osgui/oswindow.c"

#include "nappgui_src/sewer/blib.c"

#include "nappgui_src/sewer/bmem.c"

#include "nappgui_src/sewer/cassert.c"

#include "nappgui_src/sewer/ptr.c"

// ===== manual directives start =====
// Windows's (and Winelib's) windef.h file #defines an identical min macro.
#ifdef min
#undef min
#endif
// ===== manual directives end =====
#include "nappgui_src/sewer/qsort.c"
// ===== manual directives start =====
// The NAppGUI authors are lazy and didn't bother to re-enable warn.hxx
// at the end of sewer/qsort.c. This only matters for unity builds though,
// so it's kind of unreasonable to expect that from them anyway.
#include "nappgui_src/sewer/warn.hxx"
// ===== manual directives end =====

#define i_NUM_USERS i_NUM_USERS_sewer
#include "nappgui_src/sewer/sewer.c"
#undef i_NUM_USERS

#include "nappgui_src/sewer/types.c"

#include "nappgui_src/sewer/unicode.c"

#include "nappgui_src/inet/win/oshttpreq.c"

#include "nappgui_src/ogl3d/win/ogl3dimp.c"

#define i_terminate i_terminate_osapp_win
#include "nappgui_src/osapp/win/osapp_win.c"
#undef i_terminate

#include "nappgui_src/osbs/win/bfile.c"

#include "nappgui_src/osbs/win/bmutex.c"

#define i_create i_create_bproc
#include "nappgui_src/osbs/win/bproc.c"
#undef i_create

#include "nappgui_src/osbs/win/bsocket.c"

#include "nappgui_src/osbs/win/bthread.c"

#include "nappgui_src/osbs/win/btime.c"

#include "nappgui_src/osbs/win/dlib.c"

#include "nappgui_src/osbs/win/sinfo.c"

#define i_set_image i_set_image_osbutton
#include "nappgui_src/osgui/win/osbutton.c"
#undef i_set_image

#define i_WndProc i_WndProc_oscombo
#include "nappgui_src/osgui/win/oscombo.c"
#undef i_WndProc

#include "nappgui_src/osgui/win/oscomwin.c"

#define i_WndProc i_WndProc_osedit
#define i_get_cursor_pos i_get_cursor_pos_osedit
#define i_set_cursor_pos i_set_cursor_pos_osedit
#include "nappgui_src/osgui/win/osedit.c"
#undef i_WndProc
#undef i_get_cursor_pos
#undef i_set_cursor_pos

#include "nappgui_src/osgui/win/osglobals.c"

#include "nappgui_src/osgui/win/osimglist.c"

#define i_style i_style_oslabel
#define i_is_mouse_sensible i_is_mouse_sensible_oslabel
#define i_OnClick i_OnClick_oslabel
#define i_WndProc i_WndProc_oslabel
#include "nappgui_src/osgui/win/oslabel.c"
#undef i_style
#undef i_is_mouse_sensible
#undef i_OnClick
#undef i_WndProc

#include "nappgui_src/osgui/win/oslistener.c"

#include "nappgui_src/osgui/win/osmenu.c"

#define i_create i_create_osmenuitem
#include "nappgui_src/osgui/win/osmenuitem.c"
#undef i_create

#define i_WndProc i_WndProc_ospanel
#include "nappgui_src/osgui/win/ospanel.c"
#undef i_WndProc

#define i_WndProc i_WndProc_ospopup
#define i_ComboWndProc i_ComboWndProc_ospopup
#include "nappgui_src/osgui/win/ospopup.c"
#undef i_WndProc
#undef i_ComboWndProc

#include "nappgui_src/osgui/win/osprogress.c"

#include "nappgui_src/osgui/win/osscroll.c"

#define i_WndProc i_WndProc_osslider
#include "nappgui_src/osgui/win/osslider.c"
#undef i_WndProc

#define i_WndProc i_WndProc_ossplit
#include "nappgui_src/osgui/win/ossplit.c"
#undef i_WndProc

#include "nappgui_src/osgui/win/osstyleXP.c"

#define i_WndProc i_WndProc_ostext
#define i_get_cursor_pos i_get_cursor_pos_ostext
#include "nappgui_src/osgui/win/ostext.c"
#undef i_WndProc
#undef i_get_cursor_pos

#include "nappgui_src/osgui/win/ostooltip.c"

#define i_WndProc i_WndProc_osupdown
#include "nappgui_src/osgui/win/osupdown.c"
#undef i_WndProc

#define i_WndProc i_WndProc_oswindow
#include "nappgui_src/osgui/win/oswindow.c"
#undef i_WndProc

#include "nappgui_src/sewer/win/bmem_win.c"

#include "nappgui_src/sewer/win/bstdimp.c"

#define i_OnDraw i_OnDraw_colorview
#define i_OnSize i_OnSize_colorview
#define i_create i_create_colorview
#define i_destroy i_destroy_colorview
//#define i_create i_create_colorview
//#define i_destroy i_destroy_colorview
//#define Cell Cell_colorview
#include "colorview.c"
#undef i_OnDraw
#undef i_OnSize
#undef i_create
#undef i_destroy
//#undef i_create
//#undef i_destroy
//#undef Cell
