// Autogenerated by gen_inc.c

// Useful macro utilities
#ifndef _STR
#   define _STR(text) #text
#endif
#ifndef XSTR
#   define XSTR(text) _STR(text)
#endif

#include XSTR(PANGO_H_DIR/pango/pango-modules.h)

